namespace Ds2.LightHouse.PdfStrategies

open System
open System.IO
open System.Text
open System.Text.RegularExpressions
open Ds2.LightHouse
open Ds2.LightHouse.Diagnostics
open Ds2.LightHouse.Extractors.XlsxStrategies

/// **PR-I2 (todo-documents-based-gfm.md §2 + documents-based-gfm.md §8.5/§8.5.6/§8.5.7)** —
/// 광명2 전동화공장 제어시스템 PDF (자료 B) 를 어휘 SSOT + 페이지 인용 markdown 으로 정제.
///
/// **입력 가정** (`documents-based-gfm.md` §8.5):
///   - pdf, PowerPoint export 가정 (text-layer 보유, M13 default 정합).
///   - "광명2 차체공장 표준 심벌" 키워드 + "(①설비/라인/제어반)_(②부품명)_…" 명명 규칙 패턴.
///   - P45-50 = 어휘 SSOT (설비/라인/제어반 코드 ↔ 한국어), P61 = 작업순서, P104 = IO 수량 표.
///
/// **출력** (`documents-based-gfm.md` §8.5.5 강제 머리말 5행 + footer 2행):
///   ```
///   <!-- generated by PdfControlSpecStrategy v1.0.0 at <ISO8601> -->
///   <!-- source: <filename> (docId: <8-char-hash>) -->
///   <!-- signature: PdfControlSpecStrategy:<score>/9 -->
///   <!-- estimated-tokens: <approx> -->
///   <!-- strategy-version: PdfControlSpecStrategy v1.0.0 -->
///
///   # 광명2 제어시스템 표준 — <doc title>
///
///   > 광명2 차체공장 제어시스템 표준 심벌 / 명명 규칙 / 작업순서. 페이지 인용 = (P\d+).
///
///   ## 표준 심벌 (P45-P50)
///   ...
///   ```
///
/// **signature weighting** (`documents-based-gfm.md` §8.5.7):
///   - "광명2 차체공장 표준 심벌" 키워드 (또는 "표준 심벌") → +3
///   - "(①설비/라인/제어반)_(②부품명)" 명명 규칙 패턴 → +2
///   - 페이지 ≥ 30 → +2
///   - zone 코드 (`S\d{3}` / `S_OTR` 등) 출현 ≥ 5 → +1
///   - "IO LIST" / "I/O LIST" 키워드 → +1
///   threshold ≥ 6 → match.
type PdfControlSpecStrategy() =

    static let strategyName = "PdfControlSpecStrategy"
    static let strategyVersion = "1.0.0"
    static let signatureThreshold = 6
    static let signatureMaxScore = 9

    // ── signature detector helpers ──────────────────────────────────────────

    /// "광명2 차체공장 표준 심벌" 또는 "표준 심벌" 키워드 매치 (전체 segment 합산).
    static let containsStandardSymbolKeyword (segments: ExtractedSegment array) : bool =
        segments
        |> Array.exists (fun seg ->
            seg.Text.Contains("광명2 차체공장 표준 심벌")
            || seg.Text.Contains("광명2차체공장 표준 심벌")
            || seg.Text.Contains("표준 심벌"))

    /// "(①설비/라인/제어반)_(②부품명)" 명명 규칙 패턴 — 본 문구 또는 ①② 마커가 포함된 표준 명명 규칙 표현.
    static let containsNamingRulePattern (segments: ExtractedSegment array) : bool =
        let pattern = Regex(@"①.{0,30}_.{0,30}②|①\s*(설비|라인|제어반)")
        segments
        |> Array.exists (fun seg -> pattern.IsMatch(seg.Text))

    /// zone code 출현 수 — `S\d{3}` 패턴.
    static let countZoneCodeOccurrences (segments: ExtractedSegment array) : int =
        let pattern = Regex(@"\bS\d{3}\b")
        segments
        |> Array.sumBy (fun seg -> pattern.Matches(seg.Text).Count)

    /// "IO LIST" 키워드 매치.
    static let containsIoListKeyword (segments: ExtractedSegment array) : bool =
        segments
        |> Array.exists (fun seg ->
            seg.Text.Contains("I/O LIST", StringComparison.OrdinalIgnoreCase)
            || seg.Text.Contains("IO LIST", StringComparison.OrdinalIgnoreCase))

    // ── markdown builder helpers ────────────────────────────────────────────
    // **PR-I2.5**: docId / fullHash / estimateTokens 3종 helper 는 `StrategyMarkdown.fs` SSOT 위임
    // (3 strategy 공용). 본 strategy 는 호출만.

    /// segment.RefLocator (`p=14`) → 페이지 번호 추출. 실패 시 0.
    static let pageNumberOf (refLoc: string) : int =
        let m = Regex.Match(refLoc, @"^p=(\d+)$")
        if m.Success then Int32.Parse(m.Groups.[1].Value) else 0

    /// 페이지 텍스트의 한 줄 요약 (첫 비공백 line ≤ 80 chars).
    static let summarizeFirstLine (text: string) : string =
        if String.IsNullOrWhiteSpace text then "(빈 페이지)"
        else
            let firstLine =
                text.Split([| '\n' |])
                |> Array.tryFind (fun l -> not (String.IsNullOrWhiteSpace l))
                |> Option.defaultValue ""
            let trimmed = firstLine.Trim()
            if trimmed.Length > 80 then trimmed.Substring(0, 80) + "..." else trimmed

    /// 페이지 텍스트 안 zone code 추출 (distinct, 정렬). 후속 markdown section 에 박제.
    static let extractZoneCodes (text: string) : string list =
        if String.IsNullOrEmpty text then []
        else
            let pattern = Regex(@"\bS\d{3}\b")
            pattern.Matches(text)
            |> Seq.cast<Match>
            |> Seq.map (fun m -> m.Value)
            |> Seq.distinct
            |> Seq.sort
            |> Seq.toList

    /// signature 평가 — `documents-based-gfm.md` §8.5.7 weighting.
    static let evaluateSignature (extracted: ExtractedDocument) : SignatureResult =
        let isPdf = (extracted.DocType = FileKind.Pdf)
        if not isPdf then
            { Matched = false
              Score = 0
              Threshold = signatureThreshold
              Detail = "DocType != Pdf" }
        else
            let segments = extracted.Segments
            // 1. 표준 심벌 keyword.
            let hasSymKw = containsStandardSymbolKeyword segments
            let scoreSym = if hasSymKw then 3 else 0
            // 2. 명명 규칙 패턴.
            let hasNamingRule = containsNamingRulePattern segments
            let scoreNaming = if hasNamingRule then 2 else 0
            // 3. 페이지 수.
            let pageCnt =
                match extracted.PageOrSheetCnt with
                | Some n -> n
                | None -> segments.Length
            let scorePages = if pageCnt >= 30 then 2 else 0
            // 4. zone 코드 출현.
            let zoneCnt = countZoneCodeOccurrences segments
            let scoreZone = if zoneCnt >= 5 then 1 else 0
            // 5. IO LIST keyword.
            let hasIoKw = containsIoListKeyword segments
            let scoreIo = if hasIoKw then 1 else 0

            let total = scoreSym + scoreNaming + scorePages + scoreZone + scoreIo
            let detail =
                sprintf "standardSymbolKw=%b(+%d), namingRule=%b(+%d), pageCnt=%d(+%d), zoneOccurrences=%d(+%d), ioListKw=%b(+%d) = %d / %d"
                    hasSymKw scoreSym
                    hasNamingRule scoreNaming
                    pageCnt scorePages
                    zoneCnt scoreZone
                    hasIoKw scoreIo
                    total signatureMaxScore
            { Matched = total >= signatureThreshold
              Score = total
              Threshold = signatureThreshold
              Detail = detail }

    /// project name 추정 — Title 우선 / filename fallback.
    static let inferDocTitle (sourcePath: string) (extracted: ExtractedDocument) : string =
        match extracted.Title with
        | Some t when t.Length > 0 -> t
        | _ -> Path.GetFileNameWithoutExtension sourcePath

    /// markdown 빌드 진입점.
    /// 페이지를 page number 순으로 정렬 후 (P\d+) 인용 형식으로 박제.
    /// 본 PoC 의 핵심 section:
    ///   - H2 "## 페이지별 요약" — 각 페이지의 첫 줄 요약 + zone code list (P89-P104 spot-check 대상)
    ///   - H2 "## 발견 zone 코드 (전체)" — distinct zone 코드 sorted + 첫 출현 페이지
    /// **PR-I2.5**: header / footer / docId / fullHash / estimateTokens 는 `StrategyMarkdown` SSOT 위임.
    /// markdown 출력 byte-equal 유지.
    static let buildMarkdown
        (sourcePath: string)
        (extracted: ExtractedDocument)
        (sigResult: SignatureResult) : string =
        let docId = StrategyMarkdown.computeDocId sourcePath
        let fullHash = StrategyMarkdown.computeFullHash sourcePath
        let filename = Path.GetFileName sourcePath
        let title = inferDocTitle sourcePath extracted
        let nowIso = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")

        // 페이지 번호 매핑 + 정렬.
        let pages =
            extracted.Segments
            |> Array.map (fun seg -> pageNumberOf seg.RefLocator, seg.Text)
            |> Array.filter (fun (p, _) -> p > 0)
            |> Array.sortBy fst

        let body = StringBuilder()
        body.AppendLine(sprintf "# 광명2 제어시스템 표준 — %s" title) |> ignore
        body.AppendLine() |> ignore
        body.AppendLine(
            "> 광명2 차체공장 제어시스템 표준 심벌 / 명명 규칙 / 작업순서. 페이지 인용 = (P\\d+).") |> ignore
        body.AppendLine() |> ignore

        // ── H2 페이지별 요약 ────────────────────────────────────────────────
        body.AppendLine("## 페이지별 요약") |> ignore
        body.AppendLine() |> ignore
        body.AppendLine("| Page | 첫 줄 요약 | 발견 Zone 코드 |") |> ignore
        body.AppendLine("|---:|:---|:---|") |> ignore
        for (p, text) in pages do
            let summary = summarizeFirstLine text
            let zones = extractZoneCodes text
            let zoneStr = if List.isEmpty zones then "-" else String.concat ", " zones
            // markdown table | escape.
            let escSummary = summary.Replace("|", @"\|")
            body.AppendLine(sprintf "| P%d | %s | %s |" p escSummary zoneStr) |> ignore
        body.AppendLine() |> ignore

        // ── H2 발견 zone 코드 (전체 distinct) ────────────────────────────────
        let allZones =
            pages
            |> Array.collect (fun (p, text) ->
                extractZoneCodes text
                |> List.map (fun z -> z, p)
                |> List.toArray)
            |> Array.groupBy fst
            |> Array.map (fun (z, items) ->
                let firstPage = items |> Array.map snd |> Array.min
                let pageCnt = items.Length
                z, firstPage, pageCnt)
            |> Array.sortBy (fun (z, _, _) -> z)

        body.AppendLine("## 발견 Zone 코드 (전체 distinct)") |> ignore
        body.AppendLine() |> ignore
        if Array.isEmpty allZones then
            body.AppendLine("> zone 코드 (`S\\d{3}` 패턴) 미검출.") |> ignore
        else
            body.AppendLine("| Zone | 첫 출현 Page | 출현 횟수 |") |> ignore
            body.AppendLine("|:---|---:|---:|") |> ignore
            for (z, firstP, cnt) in allZones do
                body.AppendLine(sprintf "| %s | P%d | %d |" z firstP cnt) |> ignore
        body.AppendLine() |> ignore

        let bodyStr = body.ToString()
        let estTokens = StrategyMarkdown.estimateTokens bodyStr

        let header = StrategyMarkdown.buildHeader {
            StrategyName = strategyName
            StrategyVersion = strategyVersion
            NowIso = nowIso
            Filename = filename
            DocId = docId
            SignatureScore = sigResult.Score
            SignatureMaxScore = signatureMaxScore
            EstimatedTokens = estTokens
        }
        let footer = StrategyMarkdown.buildFooter {
            FullHash = fullHash
            NowIso = nowIso
        }
        let raw = header.ToString() + bodyStr + footer.ToString()
        // **Backlog H (todo-documents-based-gfm.md §6.1 + documents-based-gfm.md §8.5.5)** —
        // 자료 B (광명2 전동화공장 제어시스템 PDF) 의 raw markdown 이 cap 초과 시 자동 압축.
        // MarkdownCapPolicy 의 3 단계 (column truncate → head/tail sample → split) escalation.
        // Stage 3 진입 시 part 1 markdown 만 반환 — SplitParts 박제 hook 은 Backlog I 후속 (IPdfStrategy
        // signature 변경 + TextDumper 의 part 파일 박제 path).
        let capResult = MarkdownCapPolicy.applyCap raw
        capResult.Markdown

    interface IPdfStrategy with
        member _.Name = strategyName
        member _.Version = strategyVersion
        member _.Signature extracted = evaluateSignature extracted
        member _.Build (sourcePath, extracted) =
            let sigResult = evaluateSignature extracted
            if not sigResult.Matched then
                StrategyOutcome.Rejected {
                    File = sourcePath
                    Sheet = None
                    Reason = sprintf "signature 미매치: %s" sigResult.Detail
                    Strategy = strategyName
                    RejectedAt = DateTime.UtcNow
                }
            else
                StrategyOutcome.Built (buildMarkdown sourcePath extracted sigResult)
