module Ds2.LightHouse.Tests.MarkdownCapPolicyTests

open System
open System.Text
open Xunit
open Ds2.LightHouse

/// **Backlog D (todo-documents-based-gfm.md §6.1 N5 + documents-based-gfm.md §8.5.5)** —
/// `MarkdownCapPolicy.fs` 의 4 stage escalation 회귀.
///
/// 검증 시나리오:
///   1. Stage 0 (Original) — cap 안 markdown 은 no-op (byte-equal 반환).
///   2. Stage 1 (ColumnTruncated) — cell 안 char 길이 truncate 후 cap 안 들어감.
///   3. Stage 2 (Sampled) — column truncate 후도 초과 → row sampling 후 cap 안 들어감.
///   4. Stage 3 (Split) — sampling 후도 초과 → N 등분 split.
///   5. 표 무결성 — header row / alignment row 모든 단계에서 보존.
///   6. 표 외 line (H1/H2/quote/comment) 보존.

// ── helper — synthetic markdown fixture 생성 ────────────────────────────

/// 가상 IoListStrategy markdown 생성. `dataRows` = 표 data row 개수. `cellPad` = data cell 의
/// 추가 padding 길이 (Stage 1 trigger 용 — 80 char 이상 만들면 truncate).
let private makeFixture (dataRows: int) (cellPad: int) : string =
    let sb = StringBuilder()
    // header 5행 (real strategy header pattern 모사).
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# IO List — test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("> ***REDACTED***2 SIDE OUTER SV IO List.") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("## S201_TEST") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("| Word | Direction | Tag | DataType | Address | Symbol |") |> ignore
    sb.AppendLine("|:---|:---:|:---|:---|:---|:---|") |> ignore
    let padding = String.replicate cellPad "x"
    for i in 1 .. dataRows do
        let symbolDesc =
            if cellPad > 0 then sprintf "WRS%02d_DESC_%s" (i % 100) padding
            else sprintf "WRS%02d" (i % 100)
        sb.AppendLine(sprintf "| 2010 | Input | TAG_%d | BOOL | %%IW2010.%d | %s |"
                          i (i % 16) symbolDesc) |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    sb.AppendLine("<!-- cross-ref-hash: deadbeef -->") |> ignore
    sb.AppendLine("<!-- last-indexed: 2026-05-27T00:00:00Z -->") |> ignore
    sb.ToString()

/// 가상 multi-section IoListStrategy markdown 생성 — sectionCnt 개의 H2 section, 각 section
/// 마다 dataRows 개의 표 행. Stage 2 (head/tail + elide) 적용 후 한 section 당 ~11 행으로
/// 줄어도 section 수가 많으면 합산 size 가 cap 초과 → Stage 3 (Split) trigger.
let private makeMultiSectionFixture (sectionCnt: int) (dataRowsPerSection: int) (cellPad: int) : string =
    let sb = StringBuilder()
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# IO List — test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("> ***REDACTED***2 SIDE OUTER SV IO List.") |> ignore
    sb.AppendLine() |> ignore
    let padding = String.replicate cellPad "x"
    for s in 1 .. sectionCnt do
        sb.AppendLine(sprintf "## S%03d_TEST" s) |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("| Word | Direction | Tag | DataType | Address | Symbol |") |> ignore
        sb.AppendLine("|:---|:---:|:---|:---|:---|:---|") |> ignore
        for i in 1 .. dataRowsPerSection do
            let symbolDesc =
                if cellPad > 0 then sprintf "WRS%02d_DESC_%s" (i % 100) padding
                else sprintf "WRS%02d" (i % 100)
            sb.AppendLine(sprintf "| 2010 | Input | TAG_%d_%d | BOOL | %%IW2010.%d | %s |"
                              s i (i % 16) symbolDesc) |> ignore
        sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    sb.AppendLine("<!-- cross-ref-hash: deadbeef -->") |> ignore
    sb.AppendLine("<!-- last-indexed: 2026-05-27T00:00:00Z -->") |> ignore
    sb.ToString()

let private utf8Size (s: string) = Encoding.UTF8.GetByteCount s

// ── Stage 0 — Original (cap 안) ────────────────────────────────────────

[<Fact>]
let ``Stage 0 — cap 안 markdown 은 Original 반환 (byte-equal)`` () =
    let md = makeFixture 100 0
    Assert.True(utf8Size md < MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    Assert.Equal(MarkdownCapPolicy.Original, result.Stage)
    Assert.Equal(md, result.Markdown)
    Assert.Equal(utf8Size md, result.SizeBytes)
    Assert.Equal(None, result.SplitParts)

// ── Stage 1 — ColumnTruncated ───────────────────────────────────────────

[<Fact>]
let ``Stage 1 — 긴 cell 만 truncate, header / alignment 보존, cap 안 흡수`` () =
    // 1200 rows × cellPad 200 char → 약 320KB raw → cap 초과.
    // Stage 1 truncate (MaxCellChars=80) 후 cap 안 들어감 (각 row ~150 char × 1200 = 180KB).
    let md = makeFixture 1200 200
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture 의 raw size %d 가 cap %d 초과해야 Stage 1 trigger"
                    originalSize MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    // Stage 1 도달 검증.
    match result.Stage with
    | MarkdownCapPolicy.ColumnTruncated maxChars ->
        Assert.Equal(MarkdownCapPolicy.MaxCellChars, maxChars)
    | other ->
        Assert.Fail(sprintf "Stage 1 (ColumnTruncated) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    Assert.True(result.SizeBytes <= MarkdownCapPolicy.MaxMarkdownBytes)
    // 표 alignment row 보존.
    Assert.Contains("|:---|:---:|:---|:---|:---|:---|", result.Markdown)
    // 표 header row 보존.
    Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", result.Markdown)
    // H1 / H2 / quote / comment 보존.
    Assert.Contains("# IO List — test", result.Markdown)
    Assert.Contains("## S201_TEST", result.Markdown)
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Contains("cross-ref-hash:", result.Markdown)
    // truncate suffix 박제 확인 — 긴 cell 이 잘렸음.
    Assert.Contains("...", result.Markdown)
    // None (Split 아님).
    Assert.Equal(None, result.SplitParts)

// ── Stage 2 — Sampled (head/tail + elide, SSOT §8.5.5) ────────────────

[<Fact>]
let ``Stage 2 — head 5 + tail 5 + 중간 elide 로 cap 안 흡수 (SSOT §8.5.5 정합)`` () =
    // data row 5000 × cellPad 0 → 각 row ~70 char (Stage 1 영향 0) → raw 약 380KB.
    // Stage 1 (column truncate) 효과 미미 (cell 모두 < 80 char). → Stage 2 head/tail sampling 진입.
    // 5000 rows → head 5 + tail 5 + elide 1 row = 11 행 만 keep → cap 안 흡수 (대폭 감소).
    let md = makeFixture 5000 0
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture raw size %d 가 cap 초과해야 함" originalSize)
    let result = MarkdownCapPolicy.applyCap md
    match result.Stage with
    | MarkdownCapPolicy.Sampled (headCnt, tailCnt) ->
        Assert.Equal(MarkdownCapPolicy.SampleHeadCount, headCnt)
        Assert.Equal(MarkdownCapPolicy.SampleTailCount, tailCnt)
    | other ->
        Assert.Fail(sprintf "Stage 2 (Sampled head/tail) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    Assert.True(result.SizeBytes <= MarkdownCapPolicy.MaxMarkdownBytes)
    // 표 alignment / header row 보존.
    Assert.Contains("|:---|:---:|:---|:---|:---|:---|", result.Markdown)
    Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", result.Markdown)
    // sample note 박제 (drop 발생).
    Assert.Contains("<!-- sampled: head", result.Markdown)
    Assert.Contains("elided", result.Markdown)
    // head 5 박제 — TAG_1 ~ TAG_5 안 있음 (makeFixture i 1-base, cell 형식 `| TAG_N |`).
    Assert.Contains(" TAG_1 ", result.Markdown)
    Assert.Contains(" TAG_5 ", result.Markdown)
    // tail 5 박제 — TAG_4996 ~ TAG_5000.
    Assert.Contains(" TAG_5000 ", result.Markdown)
    Assert.Contains(" TAG_4996 ", result.Markdown)
    // 중간 row 는 drop — TAG_2500 같은 중간 row 는 사라져야 함.
    Assert.DoesNotContain(" TAG_2500 ", result.Markdown)
    // elide marker row 박제 — `(N rows elided)` 형식.
    Assert.Matches(System.Text.RegularExpressions.Regex(@"\(\d+ rows elided\)"), result.Markdown)
    // footer 보존.
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Equal(None, result.SplitParts)

// ── Stage 3 — Split ──────────────────────────────────────────────────

[<Fact>]
let ``Stage 3 — sampling 후도 초과 시 split 진입 + 각 part 가 cap 안`` () =
    // 새 Stage 2 정책 (head/tail 5 + elide) 는 단일 표를 ~11 행으로 줄여서 단일 section 만으로는
    // cap 초과 불가. Stage 3 trigger 위해 **section 수 자체가 많은** multi-section fixture 사용 —
    // 800 section × 20 row × cellPad 0. raw ~1.3MB → cap 초과 (Stage 0 fail). Stage 1 효과 0 (cell 짧음).
    // Stage 2 후 800 section × 11 row × ~80 byte + H2 overhead = ~720KB → cap 256KB 초과 → Stage 3 trigger.
    // Stage 3 partCount=ceil(1.3MB / 256KB) ≈ 6 part 로 split 성공 (SplitMaxParts=32 안).
    let md = makeMultiSectionFixture 800 20 0
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture raw size %d 가 cap 초과해야 Stage 3 trigger" originalSize)
    let result = MarkdownCapPolicy.applyCap md
    match result.Stage with
    | MarkdownCapPolicy.Split (partIdx, partCount) ->
        Assert.Equal(1, partIdx)  // 첫 part.
        Assert.True(partCount >= 2 && partCount <= MarkdownCapPolicy.SplitMaxParts,
                    sprintf "partCount=%d 가 [2, %d] 범위" partCount MarkdownCapPolicy.SplitMaxParts)
    | other ->
        Assert.Fail(sprintf "Stage 3 (Split) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    // SplitParts 는 Some.
    match result.SplitParts with
    | Some parts ->
        Assert.True(parts.Length >= 2, "split 결과 part 개수 ≥ 2")
        // 각 part 가 cap 안.
        for part in parts do
            Assert.True(utf8Size part <= MarkdownCapPolicy.MaxMarkdownBytes,
                        sprintf "part size %d 가 cap %d 초과"
                            (utf8Size part) MarkdownCapPolicy.MaxMarkdownBytes)
            // 각 part 가 header / alignment / footer 공유.
            Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", part)
            Assert.Contains("|:---|:---:|:---|:---|:---|:---|", part)
            Assert.Contains("<!-- footer -->", part)
            // split note 박제.
            Assert.Contains("<!-- split: part", part)
    | None ->
        Assert.Fail("Stage 3 (Split) 인데 SplitParts = None")

// ── 표 무결성 cross-cut ─────────────────────────────────────────────

[<Fact>]
let ``표 무결성 — Stage 1 적용 후 cell 개수 (alignment row 기준 6) 보존`` () =
    let md = makeFixture 500 150
    let result = MarkdownCapPolicy.applyCap md
    // 결과 markdown 의 모든 표 row 가 6 cell (alignment row 기준).
    let lines = result.Markdown.Split([| '\n' |]) |> Array.map (fun l -> l.TrimEnd('\r'))
    let tableRows =
        lines
        |> Array.filter (fun l -> l.StartsWith "|" && l.Contains("|") && not (l.Contains("---")))
    for row in tableRows do
        let cellCount =
            row.Split('|')
            |> Array.filter (fun s -> s.Length > 0)
            |> Array.length
        Assert.Equal(6, cellCount)

[<Fact>]
let ``표 외 line 보존 — H1 / H2 / quote / comment 가 모든 Stage 결과에 존재`` () =
    let md = makeFixture 5000 0
    let result = MarkdownCapPolicy.applyCap md
    Assert.Contains("# IO List — test", result.Markdown)
    Assert.Contains("## S201_TEST", result.Markdown)
    Assert.Contains("> ***REDACTED***2 SIDE OUTER SV IO List.", result.Markdown)
    Assert.Contains("<!-- generated by IoListStrategy", result.Markdown)
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Contains("<!-- last-indexed:", result.Markdown)

// ── SSOT 상수 회귀 ─────────────────────────────────────────────────

[<Fact>]
let ``MaxMarkdownBytes = 256 KB (documents-based-gfm.md §8.5.5 SSOT)`` () =
    Assert.Equal(256 * 1024, MarkdownCapPolicy.MaxMarkdownBytes)
