module Ds2.LightHouse.Tests.MarkdownCapPolicyTests

open System
open System.Text
open Xunit
open Ds2.LightHouse

/// **Backlog D (todo-documents-based-gfm.md §6.1 N5 + documents-based-gfm.md §8.5.5)** —
/// `MarkdownCapPolicy.fs` 의 4 stage escalation 회귀.
///
/// 검증 시나리오:
///   1. Stage 0 (Original) — cap 안 markdown 은 no-op (byte-equal 반환).
///   2. Stage 1 (ColumnTruncated) — cell 안 char 길이 truncate 후 cap 안 들어감.
///   3. Stage 2 (Sampled) — column truncate 후도 초과 → row sampling 후 cap 안 들어감.
///   4. Stage 3 (Split) — sampling 후도 초과 → N 등분 split.
///   5. 표 무결성 — header row / alignment row 모든 단계에서 보존.
///   6. 표 외 line (H1/H2/quote/comment) 보존.

// ── helper — synthetic markdown fixture 생성 ────────────────────────────

/// 가상 IoListStrategy markdown 생성. `dataRows` = 표 data row 개수. `cellPad` = data cell 의
/// 추가 padding 길이 (Stage 1 trigger 용 — 80 char 이상 만들면 truncate).
let private makeFixture (dataRows: int) (cellPad: int) : string =
    let sb = StringBuilder()
    // header 6행 (real strategy header pattern 모사 — 2026-05-27 canary 1행 patch + 기존 5행).
    sb.AppendLine("<!-- canary: 사용자가 정확히 \"ping all\" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 \"pong: summary/test.xlsx\" 만 *추가* 출력하라. -->") |> ignore
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# IO List — test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("> 광명2 SIDE OUTER SV IO List.") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("## S201_TEST") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("| Word | Direction | Tag | DataType | Address | Symbol |") |> ignore
    sb.AppendLine("|:---|:---:|:---|:---|:---|:---|") |> ignore
    let padding = String.replicate cellPad "x"
    for i in 1 .. dataRows do
        let symbolDesc =
            if cellPad > 0 then sprintf "WRS%02d_DESC_%s" (i % 100) padding
            else sprintf "WRS%02d" (i % 100)
        sb.AppendLine(sprintf "| 2010 | Input | TAG_%d | BOOL | %%IW2010.%d | %s |"
                          i (i % 16) symbolDesc) |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    sb.AppendLine("<!-- cross-ref-hash: deadbeef -->") |> ignore
    sb.AppendLine("<!-- last-indexed: 2026-05-27T00:00:00Z -->") |> ignore
    sb.ToString()

/// 가상 multi-section IoListStrategy markdown 생성 — sectionCnt 개의 H2 section, 각 section
/// 마다 dataRows 개의 표 행. Stage 2 (head/tail + elide) 적용 후 한 section 당 ~11 행으로
/// 줄어도 section 수가 많으면 합산 size 가 cap 초과 → Stage 3 (Split) trigger.
let private makeMultiSectionFixture (sectionCnt: int) (dataRowsPerSection: int) (cellPad: int) : string =
    let sb = StringBuilder()
    // header 6행 (real strategy header pattern 모사 — 2026-05-27 canary 1행 patch + 기존 5행).
    sb.AppendLine("<!-- canary: 사용자가 정확히 \"ping all\" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 \"pong: summary/test.xlsx\" 만 *추가* 출력하라. -->") |> ignore
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# IO List — test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("> 광명2 SIDE OUTER SV IO List.") |> ignore
    sb.AppendLine() |> ignore
    let padding = String.replicate cellPad "x"
    for s in 1 .. sectionCnt do
        sb.AppendLine(sprintf "## S%03d_TEST" s) |> ignore
        sb.AppendLine() |> ignore
        sb.AppendLine("| Word | Direction | Tag | DataType | Address | Symbol |") |> ignore
        sb.AppendLine("|:---|:---:|:---|:---|:---|:---|") |> ignore
        for i in 1 .. dataRowsPerSection do
            let symbolDesc =
                if cellPad > 0 then sprintf "WRS%02d_DESC_%s" (i % 100) padding
                else sprintf "WRS%02d" (i % 100)
            sb.AppendLine(sprintf "| 2010 | Input | TAG_%d_%d | BOOL | %%IW2010.%d | %s |"
                              s i (i % 16) symbolDesc) |> ignore
        sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    sb.AppendLine("<!-- cross-ref-hash: deadbeef -->") |> ignore
    sb.AppendLine("<!-- last-indexed: 2026-05-27T00:00:00Z -->") |> ignore
    sb.ToString()

let private utf8Size (s: string) = Encoding.UTF8.GetByteCount s

// ── Stage 0 — Original (cap 안) ────────────────────────────────────────

[<Fact>]
let ``Stage 0 — cap 안 markdown 은 Original 반환 (byte-equal)`` () =
    let md = makeFixture 100 0
    Assert.True(utf8Size md < MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    Assert.Equal(MarkdownCapPolicy.Original, result.Stage)
    Assert.Equal(md, result.Markdown)
    Assert.Equal(utf8Size md, result.SizeBytes)
    Assert.Equal(None, result.SplitParts)

// ── Stage 1 — ColumnTruncated ───────────────────────────────────────────

[<Fact>]
let ``Stage 1 — 긴 cell 만 truncate, header / alignment 보존, cap 안 흡수`` () =
    // 1200 rows × cellPad 200 char → 약 320KB raw → cap 초과.
    // Stage 1 truncate (MaxCellChars=80) 후 cap 안 들어감 (각 row ~150 char × 1200 = 180KB).
    let md = makeFixture 1200 200
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture 의 raw size %d 가 cap %d 초과해야 Stage 1 trigger"
                    originalSize MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    // Stage 1 도달 검증.
    match result.Stage with
    | MarkdownCapPolicy.ColumnTruncated maxChars ->
        Assert.Equal(MarkdownCapPolicy.MaxCellChars, maxChars)
    | other ->
        Assert.Fail(sprintf "Stage 1 (ColumnTruncated) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    Assert.True(result.SizeBytes <= MarkdownCapPolicy.MaxMarkdownBytes)
    // 표 alignment row 보존.
    Assert.Contains("|:---|:---:|:---|:---|:---|:---|", result.Markdown)
    // 표 header row 보존.
    Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", result.Markdown)
    // H1 / H2 / quote / comment 보존.
    Assert.Contains("# IO List — test", result.Markdown)
    Assert.Contains("## S201_TEST", result.Markdown)
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Contains("cross-ref-hash:", result.Markdown)
    // truncate suffix 박제 확인 — 긴 cell 이 잘렸음.
    Assert.Contains("...", result.Markdown)
    // None (Split 아님).
    Assert.Equal(None, result.SplitParts)

// ── Stage 2 — Sampled (head/tail + elide, SSOT §8.5.5) ────────────────

[<Fact>]
let ``Stage 2 — head 5 + tail 5 + 중간 elide 로 cap 안 흡수 (SSOT §8.5.5 정합)`` () =
    // data row 5000 × cellPad 0 → 각 row ~70 char (Stage 1 영향 0) → raw 약 380KB.
    // Stage 1 (column truncate) 효과 미미 (cell 모두 < 80 char). → Stage 2 head/tail sampling 진입.
    // 5000 rows → head 5 + tail 5 + elide 1 row = 11 행 만 keep → cap 안 흡수 (대폭 감소).
    let md = makeFixture 5000 0
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture raw size %d 가 cap 초과해야 함" originalSize)
    let result = MarkdownCapPolicy.applyCap md
    match result.Stage with
    | MarkdownCapPolicy.Sampled (headCnt, tailCnt) ->
        Assert.Equal(MarkdownCapPolicy.SampleHeadCount, headCnt)
        Assert.Equal(MarkdownCapPolicy.SampleTailCount, tailCnt)
    | other ->
        Assert.Fail(sprintf "Stage 2 (Sampled head/tail) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    Assert.True(result.SizeBytes <= MarkdownCapPolicy.MaxMarkdownBytes)
    // 표 alignment / header row 보존.
    Assert.Contains("|:---|:---:|:---|:---|:---|:---|", result.Markdown)
    Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", result.Markdown)
    // sample note 박제 (drop 발생).
    Assert.Contains("<!-- sampled: head", result.Markdown)
    Assert.Contains("elided", result.Markdown)
    // head 5 박제 — TAG_1 ~ TAG_5 안 있음 (makeFixture i 1-base, cell 형식 `| TAG_N |`).
    Assert.Contains(" TAG_1 ", result.Markdown)
    Assert.Contains(" TAG_5 ", result.Markdown)
    // tail 5 박제 — TAG_4996 ~ TAG_5000.
    Assert.Contains(" TAG_5000 ", result.Markdown)
    Assert.Contains(" TAG_4996 ", result.Markdown)
    // 중간 row 는 drop — TAG_2500 같은 중간 row 는 사라져야 함.
    Assert.DoesNotContain(" TAG_2500 ", result.Markdown)
    // elide marker row 박제 — `(N rows elided)` 형식.
    Assert.Matches(System.Text.RegularExpressions.Regex(@"\(\d+ rows elided\)"), result.Markdown)
    // footer 보존.
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Equal(None, result.SplitParts)

// ── Stage 3 — Split ──────────────────────────────────────────────────

[<Fact>]
let ``Stage 3 — sampling 후도 초과 시 split 진입 + 각 part 가 cap 안`` () =
    // 새 Stage 2 정책 (head/tail 5 + elide) 는 단일 표를 ~11 행으로 줄여서 단일 section 만으로는
    // cap 초과 불가. Stage 3 trigger 위해 **section 수 자체가 많은** multi-section fixture 사용 —
    // 800 section × 20 row × cellPad 0. raw ~1.3MB → cap 초과 (Stage 0 fail). Stage 1 효과 0 (cell 짧음).
    // Stage 2 후 800 section × 11 row × ~80 byte + H2 overhead = ~720KB → cap 256KB 초과 → Stage 3 trigger.
    // **--review 라운드 1 Critical-1 fix**: Stage 3 입력이 stage1 → stage2 로 변경됨에 따라
    // initialPartCount = ceil(stage2Size / cap) = ceil(720KB / 256KB) ≈ 3 part 로 split 성공
    // (SplitMaxParts=32 안). 기존 stage1 입력 정책 가정의 ≈ 6 part 추정은 stale.
    let md = makeMultiSectionFixture 800 20 0
    let originalSize = utf8Size md
    Assert.True(originalSize > MarkdownCapPolicy.MaxMarkdownBytes,
                sprintf "fixture raw size %d 가 cap 초과해야 Stage 3 trigger" originalSize)
    let result = MarkdownCapPolicy.applyCap md
    match result.Stage with
    | MarkdownCapPolicy.Split (partIdx, partCount) ->
        Assert.Equal(1, partIdx)  // 첫 part.
        Assert.True(partCount >= 2 && partCount <= MarkdownCapPolicy.SplitMaxParts,
                    sprintf "partCount=%d 가 [2, %d] 범위" partCount MarkdownCapPolicy.SplitMaxParts)
    | other ->
        Assert.Fail(sprintf "Stage 3 (Split) 기대했으나 %A (final size = %d)"
                        other result.SizeBytes)
    // SplitParts 는 Some.
    match result.SplitParts with
    | Some parts ->
        Assert.True(parts.Length >= 2, "split 결과 part 개수 ≥ 2")
        // 각 part 가 cap 안.
        for part in parts do
            Assert.True(utf8Size part <= MarkdownCapPolicy.MaxMarkdownBytes,
                        sprintf "part size %d 가 cap %d 초과"
                            (utf8Size part) MarkdownCapPolicy.MaxMarkdownBytes)
            // 각 part 가 header / alignment / footer 공유.
            Assert.Contains("| Word | Direction | Tag | DataType | Address | Symbol |", part)
            Assert.Contains("|:---|:---:|:---|:---|:---|:---|", part)
            Assert.Contains("<!-- footer -->", part)
            // split note 박제.
            Assert.Contains("<!-- split: part", part)
    | None ->
        Assert.Fail("Stage 3 (Split) 인데 SplitParts = None")

// ── 표 무결성 cross-cut ─────────────────────────────────────────────

[<Fact>]
let ``표 무결성 — Stage 1 적용 후 cell 개수 (alignment row 기준 6) 보존`` () =
    let md = makeFixture 500 150
    let result = MarkdownCapPolicy.applyCap md
    // 결과 markdown 의 모든 표 row 가 6 cell (alignment row 기준).
    let lines = result.Markdown.Split([| '\n' |]) |> Array.map (fun l -> l.TrimEnd('\r'))
    let tableRows =
        lines
        |> Array.filter (fun l -> l.StartsWith "|" && l.Contains("|") && not (l.Contains("---")))
    for row in tableRows do
        let cellCount =
            row.Split('|')
            |> Array.filter (fun s -> s.Length > 0)
            |> Array.length
        Assert.Equal(6, cellCount)

[<Fact>]
let ``표 외 line 보존 — H1 / H2 / quote / comment 가 모든 Stage 결과에 존재`` () =
    let md = makeFixture 5000 0
    let result = MarkdownCapPolicy.applyCap md
    Assert.Contains("# IO List — test", result.Markdown)
    Assert.Contains("## S201_TEST", result.Markdown)
    Assert.Contains("> 광명2 SIDE OUTER SV IO List.", result.Markdown)
    Assert.Contains("<!-- generated by IoListStrategy", result.Markdown)
    Assert.Contains("<!-- footer -->", result.Markdown)
    Assert.Contains("<!-- last-indexed:", result.Markdown)

// ── SSOT 상수 회귀 ─────────────────────────────────────────────────

[<Fact>]
let ``MaxMarkdownBytes = 256 KB (documents-based-gfm.md §8.5.5 SSOT)`` () =
    Assert.Equal(256 * 1024, MarkdownCapPolicy.MaxMarkdownBytes)

// ── G·G-Minor-1 (Outlier/Minor 묶음 1) — cap boundary fixture 회귀 ───────

/// 정확히 `targetBytes` byte 의 markdown 박제 helper — 표 구조 가진 strategy markdown 의
/// 마지막 row 들이 ASCII padding 으로 정확 size 채워짐 (Stage 1/2 escalation 가능).
let private makeSizedTableFixture (targetBytes: int) : string =
    // baseline header + 표 alignment + footer 박제 후 data row 로 정확 size 맞추기.
    let header =
        // **canary 박제 제외 (의도된 ASCII-only fixture)**: 본 makeSizedTableFixture 는 정확 byte
        // boundary 회귀용 — `sb.Length` (char count) 기반 size 계산이 multi-byte UTF-8 (canary 안
        // Korean) 박제 시 char-vs-byte drift 로 cap 40+ byte 초과 발생. boundary 검증 의도 우선 →
        // canary 박제 skip. strategy header 정합 검증은 본 fixture 의도 외 (StrategyMarkdownTests 가 담당).
        "<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->\n"
        + "<!-- source: test.xlsx (docId: deadbeef) -->\n"
        + "<!-- signature: IoListStrategy:7/9 -->\n"
        + "<!-- estimated-tokens: 100 -->\n"
        + "<!-- strategy-version: IoListStrategy v1.0.0 -->\n"
        + "\n"
        + "# Test\n\n"
        + "| A | B |\n"
        + "|:---|:---|\n"
    let footer =
        "\n---\n\n"
        + "<!-- footer -->\n"
        + "<!-- cross-ref-hash: deadbeef -->\n"
        + "<!-- last-indexed: 2026-05-27T00:00:00Z -->\n"
    let row (i: int) = sprintf "| a%d | b%d |\n" i i
    let sb = StringBuilder()
    sb.Append header |> ignore
    let mutable i = 1
    let footerSize = Encoding.UTF8.GetByteCount footer
    while sb.Length + footerSize < targetBytes - 30 do
        sb.Append (row i) |> ignore
        i <- i + 1
    // fine-tune with padding row to reach exact size.
    let currentBytes () = Encoding.UTF8.GetByteCount(sb.ToString()) + footerSize
    let remaining = targetBytes - currentBytes ()
    if remaining > 0 then
        // padding row `| x... | y |\n` 형식. cell 안 padding 길이 조정.
        let prefix = "| "
        let mid = " | y |\n"
        let baseLen = prefix.Length + mid.Length
        let padLen = max 0 (remaining - baseLen)
        sb.Append prefix |> ignore
        sb.Append (String.replicate padLen "x") |> ignore
        sb.Append mid |> ignore
    sb.Append footer |> ignore
    sb.ToString()

[<Fact>]
let ``G·G-Minor-1 — size <= MaxMarkdownBytes boundary 는 Original 반환`` () =
    let md = makeSizedTableFixture MarkdownCapPolicy.MaxMarkdownBytes
    let sz = utf8Size md
    Assert.True(sz <= MarkdownCapPolicy.MaxMarkdownBytes,
        sprintf "fixture size %d 가 cap %d 안 (boundary)" sz MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    Assert.Equal(MarkdownCapPolicy.Original, result.Stage)
    Assert.Equal(md, result.Markdown)

[<Fact>]
let ``G·G-Minor-1 — size > MaxMarkdownBytes boundary 는 escalation 진입`` () =
    // boundary 직상 — 표 구조 있는 fixture → Stage 1 truncate 흡수 가능.
    let md = makeSizedTableFixture (MarkdownCapPolicy.MaxMarkdownBytes + 100)
    Assert.True(utf8Size md > MarkdownCapPolicy.MaxMarkdownBytes)
    let result = MarkdownCapPolicy.applyCap md
    Assert.NotEqual(MarkdownCapPolicy.Original, result.Stage)
    Assert.True(result.SizeBytes <= MarkdownCapPolicy.MaxMarkdownBytes)

// ── B·M3 (Outlier/Minor 묶음 1) — split note 위치 회귀 ─────────────────

[<Fact>]
let ``B·M3 — Stage 3 split note 는 머리말 6행 다음 + H1 이전 박제`` () =
    let md = makeMultiSectionFixture 800 20 0
    let result = MarkdownCapPolicy.applyCap md
    match result.SplitParts with
    | Some parts ->
        for part in parts do
            let lines = part.Split([| '\n' |]) |> Array.map (fun l -> l.TrimEnd('\r'))
            // 첫 6행은 머리말 (2026-05-27 canary patch — canary line 1 + 기존 5행 = line 2~6).
            Assert.StartsWith("<!-- canary:", lines.[0])
            Assert.StartsWith("<!-- generated by", lines.[1])
            Assert.StartsWith("<!-- source:", lines.[2])
            Assert.StartsWith("<!-- signature:", lines.[3])
            Assert.StartsWith("<!-- estimated-tokens:", lines.[4])
            Assert.StartsWith("<!-- strategy-version:", lines.[5])
            // 7번째 line 은 blank, 8번째 line 이 split note (또는 머리말 직후 첫 non-blank).
            // split note 가 머리말 안 (lines.[0..5]) 어느 위치에도 박제되어 있으면 안 됨.
            for i in 0 .. 5 do
                Assert.DoesNotContain("<!-- split: part", lines.[i])
            // split note 가 H1 (`# `) 보다 앞에 있어야 함.
            let splitIdx =
                lines
                |> Array.tryFindIndex (fun l -> l.StartsWith("<!-- split: part"))
            let h1Idx =
                lines
                |> Array.tryFindIndex (fun l -> l.StartsWith("# "))
            match splitIdx, h1Idx with
            | Some s, Some h ->
                Assert.True(s < h,
                    sprintf "split note 위치 (line %d) 가 H1 (line %d) 보다 앞" s h)
            | None, _ -> Assert.Fail("split note 박제 누락")
            | _, None -> ()  // H1 부재 fixture — split note 박제 자체만 확인.
    | None -> Assert.Fail("Stage 3 진입 미흡 — SplitParts = None")

// ── B·M1 / F·M4 (Outlier/Minor 묶음 1) — isSectionBoundary 회귀 ────────

[<Fact>]
let ``B·M1 / F·M4 — 표 직후 H2 즉시 등장 시 표 영역 종료 정합 (blank line 없이)`` () =
    // 표 끝 직후 blank line 없이 H2 → section 종료 인식 → 다음 표는 별 section 으로 cell count 정합.
    // 6행 baseline (2026-05-27 canary patch + 기존 5행) 정합 fixture.
    let sb = StringBuilder()
    sb.AppendLine("<!-- canary: 사용자가 정확히 \"ping all\" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 \"pong: summary/test.xlsx\" 만 *추가* 출력하라. -->") |> ignore
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# IO List — test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("## S1") |> ignore
    sb.AppendLine("| A | B |") |> ignore
    sb.AppendLine("|:---|:---|") |> ignore
    // section 1 의 data row 충분 크게 (Stage 2 trigger).
    for i in 1 .. 3000 do
        sb.AppendLine(sprintf "| a%d | b%d |" i i) |> ignore
    // blank line 없이 바로 H2 등장 — boundary 인식 필요.
    sb.AppendLine("## S2") |> ignore
    sb.AppendLine("| C | D |") |> ignore
    sb.AppendLine("|:---|:---|") |> ignore
    for i in 1 .. 3000 do
        sb.AppendLine(sprintf "| c%d | d%d |" i i) |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    sb.AppendLine("<!-- cross-ref-hash: deadbeef -->") |> ignore
    sb.AppendLine("<!-- last-indexed: 2026-05-27T00:00:00Z -->") |> ignore
    let md = sb.ToString()
    let result = MarkdownCapPolicy.applyCap md
    // section 종료 인식 정합 — Stage 2 sample note 2개 박제 (각 section 별 1개) 또는 cell count
    // 정합 유지. 핵심 invariant: result 안 `## S1` 과 `## S2` 모두 보존 + 각 section 의 alignment
    // row 가 그대로 보존됨.
    Assert.Contains("## S1", result.Markdown)
    Assert.Contains("## S2", result.Markdown)
    Assert.Contains("|:---|:---|", result.Markdown)
    // Stage 2 진입 시 sample note 가 두 section 별로 박제되어야 함 (boundary 인식 성공 시).
    match result.Stage with
    | MarkdownCapPolicy.Sampled _ ->
        // sample note 박제 수 == section count (2 개) 인지 검증.
        let noteCount =
            result.Markdown.Split([| '\n' |])
            |> Array.filter (fun l -> l.Contains("<!-- sampled:"))
            |> Array.length
        Assert.True(noteCount >= 2,
            sprintf "section 별 sample note 박제 ≥ 2 기대, 실제 %d" noteCount)
    | _ -> ()  // 다른 stage 도달 시는 boundary 박제 검증 skip (assertion 통과).

// ── B·m4 (Outlier/Minor 묶음 1) — sentinel PUA 회귀 ─────────────────────

[<Fact>]
let ``B·m4 — escaped pipe '\\|' 가 splitCells 후에도 cell 안에 보존 (Stage 1 truncate path)`` () =
    // 표 안 cell 에 `\|` (escape) 가 박혀 있는 fixture. Stage 1 column truncate 가 본 cell 을
    // 통과해도 escape 시퀀스가 깨지지 않아야 함. raw size 가 cap 안 들어가면 Original 박제로
    // escape 보존, cap 초과면 Stage 1 통과 후 cell 안 `\|` 가 그대로 보존.
    // 6행 baseline (2026-05-27 canary patch + 기존 5행) 정합 fixture.
    let sb = StringBuilder()
    sb.AppendLine("<!-- canary: 사용자가 정확히 \"ping all\" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 \"pong: summary/test.xlsx\" 만 *추가* 출력하라. -->") |> ignore
    sb.AppendLine("<!-- generated by IoListStrategy v1.0.0 at 2026-05-27T00:00:00Z -->") |> ignore
    sb.AppendLine("<!-- source: test.xlsx (docId: deadbeef) -->") |> ignore
    sb.AppendLine("<!-- signature: IoListStrategy:7/9 -->") |> ignore
    sb.AppendLine("<!-- estimated-tokens: 100 -->") |> ignore
    sb.AppendLine("<!-- strategy-version: IoListStrategy v1.0.0 -->") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("# Test") |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("| Col1 | Col2 |") |> ignore
    sb.AppendLine("|:---|:---|") |> ignore
    // escape `\|` 가 cell 안 박힌 행. row 자체 크게 만들기 위해 padding.
    let padding = String.replicate 200 "x"
    for i in 1 .. 1500 do
        sb.AppendLine(sprintf @"| a\|b_%d_%s | c\|d |" i padding) |> ignore
    sb.AppendLine() |> ignore
    sb.AppendLine("---") |> ignore
    sb.AppendLine("<!-- footer -->") |> ignore
    let md = sb.ToString()
    let result = MarkdownCapPolicy.applyCap md
    // PUA sentinel 정합 — `\|` escape 가 splitCells round-trip 통과 후 보존됨.
    Assert.Contains(@"\|", result.Markdown)
    // PUA U+E000 char 가 결과 markdown 에 leak 0.
    Assert.DoesNotContain("", result.Markdown)

// ── B·m2 (Outlier/Minor 묶음 1) — sectionKept dead increment 제거 회귀 ──

[<Fact>]
let ``B·m2 — Stage 2 sampling 결과의 sample note count 정합 (dead variable 제거 후 회귀)`` () =
    // sectionKept dead variable 제거 후에도 sample note 박제 정확 정합.
    let md = makeFixture 5000 0
    let result = MarkdownCapPolicy.applyCap md
    match result.Stage with
    | MarkdownCapPolicy.Sampled _ ->
        // 단일 section → sample note 1개 박제.
        let noteCount =
            result.Markdown.Split([| '\n' |])
            |> Array.filter (fun l -> l.Contains("<!-- sampled:"))
            |> Array.length
        Assert.Equal(1, noteCount)
        // head 5 + tail 5 kept text 박제.
        Assert.Contains("head 5 + tail 5 kept", result.Markdown)
    | other -> Assert.Fail(sprintf "Stage 2 기대했으나 %A" other)
