module Ds2.LightHouse.Tests.PdfStrategiesTests

open System
open System.IO
open System.Threading
open System.Text.RegularExpressions
open Xunit
open Ds2.LightHouse
open Ds2.LightHouse.Diagnostics
open Ds2.LightHouse.Extractors
open Ds2.LightHouse.Extractors.XlsxStrategies
open Ds2.LightHouse.PdfStrategies

/// **PR-I2 (todo-documents-based-gfm.md §2 PR-I2 + §2.1 + §3.1)** — pdf strategy +
/// PdfSignatureClassifier + PdfControlSpecStrategy 회귀.
///
/// 검증 시나리오:
///   1. synthetic ExtractedDocument fixture — signature 매치 / 미매치 분기.
///   2. classifier 진입점 — Matched / NearMiss / Unmatched 분기.
///   3. markdown 구조 — 머리말 5행 + H1 + H2 (페이지별 요약 + 발견 zone 코드) + footer.
///   4. (옵션) 자료 B 실파일 — `F:/Git/dualsoft/secrets/KBSamples/core/3.광명2*.pdf` 존재 시 +
///      M22 spot-check 5 페이지 정합 (P89-P104 안 random 5 페이지).

// ── 합성 fixture helpers ────────────────────────────────────────────────

/// 광명2 control spec signature 충족 ExtractedDocument fixture.
///   - 110 페이지, 표준 심벌 / 명명 규칙 / zone 코드 / IO LIST 키워드 박제.
///   - 자료 B 의 P89-P104 spot-check 영역 (M22) 정합 검증을 위해 핵심 페이지 박제.
let private makeControlSpecFixture () : ExtractedDocument =
    let segments = ResizeArray<ExtractedSegment>()
    for p in 1 .. 110 do
        let text =
            match p with
            | 1 -> "광명2 차체공장 제어시스템 표준\n작성: HKMC 설비제어기술2팀"
            | 45 ->
                "광명2 차체공장 표준 심벌\n\n①설비_②부품명_③번호 명명 규칙\nWRS01: 용접 로봇\nCLP01: 클램프"
            | 46 -> "표준 심벌 (계속)\n①설비/라인/제어반\n②부품명"
            | 61 ->
                "작업 순서 (Sequence)\n1. 자재 투입\n2. 위치 결정\n3. 용접\n4. 검사"
            | 89 -> "S201 zone - RB1 (Robot 1)\n초기 위치 -> 작업 위치"
            | 90 -> "S202 zone - ARRANGE_JIG\n클램프 동작 순서"
            | 91 -> "S203 zone - WRS (Welding Workshop Station)"
            | 92 -> "S204 zone - KEY_JIG\nKEY 지그 동작"
            | 93 -> "S205 zone - RESPOT_JIG\nRESPOT 지그 동작"
            | 95 -> "S201 / S204 zone 추가 — 통합 패턴"
            | 99 -> "S204 zone — 정밀 IO 매핑"
            | 104 -> "I/O LIST 요약\nInput 총 540 비트, Output 총 280 비트\nS201 ~ S205 zone 합산"
            | _ -> sprintf "페이지 %d 본문 텍스트 한국어" p
        segments.Add {
            OutlineIndex = None
            RefLocator = sprintf "p=%d" p
            Text = text
        }
    {
        DocType = Pdf
        PageOrSheetCnt = Some 110
        Title = Some "광명2 제어시스템 표준"
        Outline = [||]
        Segments = segments.ToArray()
        Images = [||]
    }

/// signature 미매치 ExtractedDocument fixture — 일반 보고서 (zone code / 표준 심벌 없음).
let private makeNonMatchFixture () : ExtractedDocument =
    let segments = [|
        { OutlineIndex = None; RefLocator = "p=1"; Text = "회의록 — 2026-05-27" }
        { OutlineIndex = None; RefLocator = "p=2"; Text = "참석자: A, B, C\n안건: 분기 매출 분석" }
    |]
    {
        DocType = Pdf
        PageOrSheetCnt = Some 2
        Title = Some "회의록"
        Outline = [||]
        Segments = segments
        Images = [||]
    }

// ── PdfControlSpecStrategy signature + build 회귀 ────────────────────────

[<Fact>]
let ``PdfControlSpecStrategy signature — 광명2 fixture 는 매치 (score >= threshold)`` () =
    let extracted = makeControlSpecFixture ()
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    let result = strategy.Signature extracted
    Assert.True(result.Matched, sprintf "signature 미매치 — detail=%s" result.Detail)
    Assert.True(result.Score >= result.Threshold)

[<Fact>]
let ``PdfControlSpecStrategy signature — 회의록 fixture 는 미매치 (score < threshold)`` () =
    let extracted = makeNonMatchFixture ()
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    let result = strategy.Signature extracted
    Assert.False(result.Matched, sprintf "회의록 false-positive — detail=%s" result.Detail)

[<Fact>]
let ``PdfControlSpecStrategy signature — Xlsx DocType 은 0 점 (가드)`` () =
    let extracted : ExtractedDocument = {
        DocType = Xlsx
        PageOrSheetCnt = Some 30
        Title = None
        Outline = [||]
        Segments = [||]
        Images = [||]
    }
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    let result = strategy.Signature extracted
    Assert.False(result.Matched)
    Assert.Equal(0, result.Score)

[<Fact>]
let ``PdfControlSpecStrategy Build — 매치 시 markdown 반환 + 머리말 5행 강제`` () =
    let extracted = makeControlSpecFixture ()
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    let dummyPath = "fixture.pdf"
    match strategy.Build (dummyPath, extracted) with
    | StrategyOutcome.Rejected entry ->
        Assert.Fail(sprintf "Build 가 Rejected 반환 — reason=%s" entry.Reason)
    | StrategyOutcome.Built markdown ->
        let lines = markdown.Split([| '\n' |], 8)
        Assert.True(lines.Length >= 5, "최소 5 행 머리말 필요")
        Assert.Contains("generated by PdfControlSpecStrategy v", lines.[0])
        Assert.Contains("source: fixture.pdf", lines.[1])
        Assert.Contains("docId:", lines.[1])
        Assert.Contains("signature: PdfControlSpecStrategy:", lines.[2])
        Assert.Contains("estimated-tokens:", lines.[3])
        Assert.Contains("strategy-version: PdfControlSpecStrategy v", lines.[4])

[<Fact>]
let ``PdfControlSpecStrategy Build — H1 + 페이지별 요약 표 + zone 코드 표 + footer`` () =
    let extracted = makeControlSpecFixture ()
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    match strategy.Build ("fixture.pdf", extracted) with
    | StrategyOutcome.Rejected entry ->
        Assert.Fail(sprintf "Build 가 Rejected — %s" entry.Reason)
    | StrategyOutcome.Built markdown ->
        // H1 — "# 광명2 제어시스템 표준 — <title>"
        Assert.Contains("# 광명2 제어시스템 표준 —", markdown)
        // 페이지별 요약 H2.
        Assert.Contains("## 페이지별 요약", markdown)
        // 페이지 표 헤더 + alignment.
        Assert.Contains("| Page | 첫 줄 요약 | 발견 Zone 코드 |", markdown)
        Assert.Contains("|---:|:---|:---|", markdown)
        // P45 / P89 등 핵심 페이지 박제.
        Assert.Contains("| P45 |", markdown)
        Assert.Contains("| P89 |", markdown)
        Assert.Contains("| P104 |", markdown)
        // 발견 zone 코드 표.
        Assert.Contains("## 발견 Zone 코드 (전체 distinct)", markdown)
        Assert.Contains("| Zone | 첫 출현 Page | 출현 횟수 |", markdown)
        // S201 ~ S205 zone 박제 확인.
        Assert.Contains("| S201 |", markdown)
        Assert.Contains("| S204 |", markdown)
        // footer.
        Assert.Contains("<!-- footer -->", markdown)
        Assert.Contains("cross-ref-hash:", markdown)

[<Fact>]
let ``PdfControlSpecStrategy Build — 미매치 fixture 는 Rejected 반환 (정상 분기)`` () =
    let extracted = makeNonMatchFixture ()
    let strategy = PdfControlSpecStrategy() :> IPdfStrategy
    match strategy.Build ("non-match.pdf", extracted) with
    | StrategyOutcome.Built _ -> Assert.Fail("회의록 fixture 가 Built — false-positive")
    | StrategyOutcome.Rejected entry ->
        Assert.Equal("PdfControlSpecStrategy", entry.Strategy)
        Assert.Contains("signature 미매치", entry.Reason)

// ── PdfSignatureClassifier dispatch 회귀 ─────────────────────────────────

[<Fact>]
let ``PdfSignatureClassifier — PR-I2 시점 strategy list = PdfControlSpecStrategy 단독`` () =
    Assert.Equal(1, List.length PdfSignatureClassifier.strategies)
    Assert.Equal("PdfControlSpecStrategy", PdfSignatureClassifier.strategies.Head.Name)

[<Fact>]
let ``PdfSignatureClassifier — 매치 시 Matched 반환`` () =
    let extracted = makeControlSpecFixture ()
    let result = PdfSignatureClassifier.classify "fixture.pdf" extracted
    match result with
    | PdfClassificationResult.Matched (name, markdown) ->
        Assert.Equal("PdfControlSpecStrategy", name)
        Assert.True(markdown.Length > 0)
    | other -> Assert.Fail(sprintf "Matched 기대했으나 %A" other)

[<Fact>]
let ``PdfSignatureClassifier — 미매치 시 Unmatched 또는 NearMiss 반환`` () =
    let extracted = makeNonMatchFixture ()
    let result = PdfSignatureClassifier.classify "non-match.pdf" extracted
    match result with
    | PdfClassificationResult.Unmatched -> ()
    | PdfClassificationResult.NearMiss entries ->
        Assert.All(entries, fun e ->
            Assert.True(e.Score < e.Threshold))
    | other -> Assert.Fail(sprintf "Unmatched/NearMiss 기대했으나 %A" other)

// ── 자료 B 실파일 회귀 + M22 spot-check ──────────────────────────────────

let private sampleBPath =
    @"F:/Git/dualsoft/secrets/KBSamples/core/3.광명2_전동화공장_제어시스템(HMI편집됨).pdf"

let private extractPdf (path: string) : ExtractedDocument =
    use ext = new PdfExtractor() :> IExtractor
    ext.Extract(path, CancellationToken.None)

[<Fact>]
let ``자료 B 실파일 — 존재 시 PdfControlSpecStrategy 매치 + markdown 박제 e2e`` () =
    if not (File.Exists sampleBPath) then
        // 다른 머신에서 fixture 부재 — silent skip (M5 default — fixture commit 보류).
        ()
    else
        let extracted = extractPdf sampleBPath
        Assert.Equal(FileKind.Pdf, extracted.DocType)
        let result = PdfSignatureClassifier.classify sampleBPath extracted
        match result with
        | PdfClassificationResult.Matched (name, markdown) ->
            Assert.Equal("PdfControlSpecStrategy", name)
            // 머리말 5행.
            let headLines = markdown.Split([| '\n' |], 6)
            Assert.True(headLines.Length >= 5)
            Assert.Contains("generated by PdfControlSpecStrategy v", headLines.[0])
            Assert.Contains("strategy-version: PdfControlSpecStrategy v", headLines.[4])
            // 페이지별 요약 + zone 코드 표.
            Assert.Contains("## 페이지별 요약", markdown)
            Assert.Contains("## 발견 Zone 코드 (전체 distinct)", markdown)
            // 토큰 추정값 양수.
            Assert.Matches(Regex(@"estimated-tokens: \d+"), markdown)
        | other ->
            Assert.Fail(sprintf "자료 B 가 PdfControlSpecStrategy 매치 실패 — %A" other)

/// **M22 spot-check** (todo §6 메타리뷰 항목) — 자료 B 의 P89-P104 안 5 페이지 (P89/P92/P95/P99/P104) 가
/// markdown 의 "## 페이지별 요약" 표에 정합 박제되는지 확인. 자료 B 부재 시 fixture-only 회귀로 갈음.
[<Fact>]
let ``M22 spot-check — 자료 B 의 P89-P104 안 5 페이지 박제 정합`` () =
    let checkPages = [ 89; 92; 95; 99; 104 ]
    if File.Exists sampleBPath then
        let extracted = extractPdf sampleBPath
        let strategy = PdfControlSpecStrategy() :> IPdfStrategy
        match strategy.Build (sampleBPath, extracted) with
        | StrategyOutcome.Rejected entry ->
            Assert.Fail(sprintf "자료 B 가 Rejected — %s" entry.Reason)
        | StrategyOutcome.Built markdown ->
            for p in checkPages do
                let token = sprintf "| P%d |" p
                Assert.True(
                    markdown.Contains(token),
                    sprintf "M22 spot-check 페이지 P%d 가 markdown 표에 박제 누락" p)
    else
        // 자료 B 부재 — synthetic fixture 로 갈음 (P89/P92/P95/P99/P104 중 fixture 가 박제하는 P89/P104 + P92 만 확인).
        let extracted = makeControlSpecFixture ()
        let strategy = PdfControlSpecStrategy() :> IPdfStrategy
        match strategy.Build ("fixture.pdf", extracted) with
        | StrategyOutcome.Rejected entry ->
            Assert.Fail(sprintf "fixture 가 Rejected — %s" entry.Reason)
        | StrategyOutcome.Built markdown ->
            // fixture 가 정의한 P89/P92/P104 만 확인 (fixture-only 갈음 명시).
            for p in [ 89; 92; 104 ] do
                let token = sprintf "| P%d |" p
                Assert.True(
                    markdown.Contains(token),
                    sprintf "fixture 갈음: 페이지 P%d 박제 누락" p)
