module Ds2.LightHouse.Tests.UserGuideImporterTests

open System
open System.IO
open System.Security.Cryptography
open System.Text
open Xunit
open Ds2.LightHouse

do Ds2.LightHouse.Tests.TestInit.registered |> ignore

/// **PR-N15 (todo-documents-based-gfm.md §6.1 N15 + documents-based-gfm.md §8.5.4 / §8.5.5)** —
/// `UserGuideImporter.importAll` 회귀.
///
/// 검증 시나리오:
///   1. happy path: 단일 `<root>/guide/foo.md` → `_user-guide-foo.md` 박제 + 머리말 6행 + 본문 보존.
///   2. 재귀 sweep: `<root>/guide/sub/foo.md` → `_user-guide-sub-foo.md`.
///   3. 빈 디렉토리: no-op (빈 array).
///   4. 부재 디렉토리: no-op (예외 0).
///   5. cross-ref-hash 정확 — 동일 source bytes 재호출 시 hash 동일.
///   6. 멱등 — 동일 source 2회 호출 byte-identical 본문 (단 generated-at 만 갱신).
///   7. 머리말 6행 정확 형식 — 각 행 정합 assert.
///   8. SpecializedDigestBuilder ordering 회귀 — `_user-guide-*` 가 underscore prefix 로 맨 앞 박제.

// ── 공통 helpers ────────────────────────────────────────────────────────

let private withTempDir (action: string -> 'r) : 'r =
    let dir = Path.Combine(Path.GetTempPath(), sprintf "lh-ugimp-%s" (Guid.NewGuid().ToString("N")))
    Directory.CreateDirectory dir |> ignore
    try action dir
    finally
        try Directory.Delete(dir, true) with _ -> ()

let private writeGuide (root: string) (relativePath: string) (content: string) : string =
    let path = Path.Combine(root, "guide", relativePath)
    Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
    File.WriteAllText(path, content, UTF8Encoding(false))
    path

let private sha256Hex (s: string) : string =
    use sha = SHA256.Create()
    let bytes = Encoding.UTF8.GetBytes(s: string)
    let hash = sha.ComputeHash(bytes)
    let sb = StringBuilder(hash.Length * 2)
    for b in hash do sb.Append(b.ToString("x2")) |> ignore
    sb.ToString()

// ── 시나리오 1: happy path 단일 markdown ───────────────────────────────

[<Fact>]
let ``importAll - 단일 guide markdown 박제 + 머리말 6행 + 본문 보존`` () =
    withTempDir (fun root ->
        let body = "# 사용자 가이드\n\n본 문서는 ***REDACTED***2 색인 우선순위 박제 가이드."
        writeGuide root "foo.md" body |> ignore
        let results = UserGuideImporter.importAll root
        Assert.Equal(1, results.Length)
        let outPath = results.[0]
        Assert.EndsWith("_user-guide-foo.md", outPath.Replace('\\', '/'))
        let written = File.ReadAllText(outPath, Encoding.UTF8)
        // 본문 박제 확인.
        Assert.Contains(body, written)
        // 머리말 6행 + 빈 행 1 → 본문 시작 = line 8 부터.
        let lines = written.Replace("\r\n", "\n").Split('\n')
        Assert.True(lines.Length >= 7, sprintf "박제 line 수 부족: %d" lines.Length)
        Assert.StartsWith("<!-- canary:", lines.[0])
        Assert.Contains("pong: guide/foo.md", lines.[0])
        Assert.StartsWith("<!-- generated by UserGuideImporter v1.0 at ", lines.[1])
        Assert.StartsWith("<!-- source: guide/foo.md (cross-ref-hash: ", lines.[2])
        Assert.Equal("<!-- signature: userGuide:1/1 -->", lines.[3])
        Assert.StartsWith("<!-- estimated-tokens: ", lines.[4])
        Assert.Equal("<!-- strategy-version: UserGuideImporter v1.0 -->", lines.[5])
        Assert.Equal("", lines.[6]))  // 머리말 직후 빈 행.

// ── 시나리오 2: 재귀 sweep + subdir 박제 ─────────────────────────────

[<Fact>]
let ``importAll - subdir 재귀 sweep + dash 치환 박제`` () =
    withTempDir (fun root ->
        writeGuide root "top.md" "# Top" |> ignore
        writeGuide root (Path.Combine("sub", "nested.md")) "# Nested" |> ignore
        writeGuide root (Path.Combine("sub", "deep", "leaf.md")) "# Leaf" |> ignore

        let results = UserGuideImporter.importAll root |> Array.map (fun p -> Path.GetFileName p)
        Assert.Equal(3, results.Length)
        let resultSet = Set.ofArray results
        Assert.Contains("_user-guide-top.md", resultSet)
        Assert.Contains("_user-guide-sub-nested.md", resultSet)
        Assert.Contains("_user-guide-sub-deep-leaf.md", resultSet))

// ── 시나리오 3: 빈 디렉토리 → 빈 array ────────────────────────────────

[<Fact>]
let ``importAll - 빈 guide 디렉토리 no-op (빈 array)`` () =
    withTempDir (fun root ->
        Directory.CreateDirectory(Path.Combine(root, "guide")) |> ignore
        let results = UserGuideImporter.importAll root
        Assert.Empty(results))

// ── 시나리오 4: 부재 디렉토리 → 빈 array + 예외 0 ───────────────────

[<Fact>]
let ``importAll - guide 디렉토리 부재 graceful no-op`` () =
    withTempDir (fun root ->
        let results = UserGuideImporter.importAll root
        Assert.Empty(results))

// ── 시나리오 5: cross-ref-hash 정확 ──────────────────────────────────

[<Fact>]
let ``importAll - cross-ref-hash 가 source bytes SHA256 정합`` () =
    withTempDir (fun root ->
        let body = "abc123 한글 본문 hash 검증"
        writeGuide root "h.md" body |> ignore
        let results = UserGuideImporter.importAll root
        let written = File.ReadAllText(results.[0], Encoding.UTF8)
        let expectedHash = sha256Hex body
        Assert.Contains(sprintf "cross-ref-hash: %s" expectedHash, written))

// ── 시나리오 6: 멱등 ─────────────────────────────────────────────────

[<Fact>]
let ``importAll - 동일 source 재호출 시 본문 byte-identical (generated-at 행만 갱신)`` () =
    withTempDir (fun root ->
        let body = "# Idempotent\n\nstatic content"
        writeGuide root "idem.md" body |> ignore
        let r1 = UserGuideImporter.importAll root
        let c1 = File.ReadAllText(r1.[0], Encoding.UTF8)
        // 시간 차이 확보 위해 짧은 sleep (generated-at 이 다를 수 있게).
        System.Threading.Thread.Sleep(50)
        let r2 = UserGuideImporter.importAll root
        let c2 = File.ReadAllText(r2.[0], Encoding.UTF8)
        Assert.Equal(r1.[0], r2.[0])
        // 본문 + cross-ref-hash 동일 — generated-at line 2 만 다를 수 있음.
        let lines1 = c1.Replace("\r\n", "\n").Split('\n')
        let lines2 = c2.Replace("\r\n", "\n").Split('\n')
        Assert.Equal(lines1.[0], lines2.[0])  // canary
        Assert.Equal(lines1.[2], lines2.[2])  // source + cross-ref-hash
        Assert.Equal(lines1.[3], lines2.[3])  // signature
        Assert.Equal(lines1.[4], lines2.[4])  // estimated-tokens
        Assert.Equal(lines1.[5], lines2.[5])  // strategy-version
        // 본문 (line 7 이후) 도 동일.
        let body1 = String.Join("\n", lines1 |> Array.skip 7)
        let body2 = String.Join("\n", lines2 |> Array.skip 7)
        Assert.Equal(body1, body2))

// ── 시나리오 7: SpecializedDigestBuilder ordering 회귀 ────────────────

[<Fact>]
let ``SpecializedDigestBuilder - _user-guide-* 가 underscore prefix 로 alphabetical 맨 앞 박제`` () =
    withTempDir (fun root ->
        // strategy 산출물 fixture — `b1-iolist-...md` (b1 prefix 가 underscore 보다 뒤).
        let summary = TextDumper.summaryDir root
        Directory.CreateDirectory summary |> ignore
        File.WriteAllText(Path.Combine(summary, "b1-iolist.md"), "# B1 IoList", UTF8Encoding(false))
        // user-guide 박제 직전에 strategy 산출물이 이미 박제된 상태 가정.
        writeGuide root "intro.md" "# User Guide Intro" |> ignore
        let userGuideOuts = UserGuideImporter.importAll root
        Assert.Equal(1, userGuideOuts.Length)

        let digest = SpecializedDigestBuilder.build root
        Assert.Equal(2, digest.Metadata.FileCount)
        // `_user-guide-intro.md` 가 `b1-iolist.md` 보다 먼저 박제 (ASCII '_'=0x5F < 'b'=0x62).
        let idxUserGuide = digest.Combined.IndexOf("User Guide Intro")
        let idxIoList = digest.Combined.IndexOf("B1 IoList")
        Assert.True(idxUserGuide >= 0)
        Assert.True(idxIoList >= 0)
        Assert.True(idxUserGuide < idxIoList,
            sprintf "_user-guide-* 가 맨 앞 박제 의무 (idxUserGuide=%d, idxIoList=%d)" idxUserGuide idxIoList))

// ── 시나리오 8: 머리말 6행 + summary/ 절대 경로 박제 verify ───────

[<Fact>]
let ``importAll - summary 박제 위치가 .lighthouse-kb/summary/`` () =
    withTempDir (fun root ->
        writeGuide root "loc.md" "# Loc" |> ignore
        let results = UserGuideImporter.importAll root
        Assert.Equal(1, results.Length)
        let expectedDir = TextDumper.summaryDir root
        Assert.Equal(expectedDir, Path.GetDirectoryName results.[0]))

// ── 시나리오 9: 파일명 sanitize 통합 검증 (importAll 통해) ─────────

[<Fact>]
let ``importAll - 다단계 subdir 파일명 dash join 정합`` () =
    withTempDir (fun root ->
        writeGuide root (Path.Combine("a", "b", "c", "leaf.md")) "# Leaf" |> ignore
        let results = UserGuideImporter.importAll root |> Array.map (fun p -> Path.GetFileName p)
        Assert.Equal(1, results.Length)
        Assert.Equal("_user-guide-a-b-c-leaf.md", results.[0]))

// ── 시나리오 10: Classifier.isUserGuideSourcePath SSOT 회귀 ─────────

[<Fact>]
let ``Classifier - isUserGuideSourcePath SSOT 정합 (guide/* true, 그 외 false)`` () =
    withTempDir (fun root ->
        let guideFile = Path.Combine(root, "guide", "x.md")
        let nonGuideFile = Path.Combine(root, "data", "x.md")
        let nestedGuide = Path.Combine(root, "guide", "sub", "y.md")
        Assert.True(Classifier.isUserGuideSourcePath root guideFile)
        Assert.True(Classifier.isUserGuideSourcePath root nestedGuide)
        Assert.False(Classifier.isUserGuideSourcePath root nonGuideFile))
