namespace DSPilot.Engine

open System

/// Flow entity - dsp.db's dspFlow table
[<CLIMutable>]
type DspFlowEntity =
    { Id: int
      FlowName: string
      MT: int option
      WT: int option
      CT: int option
      State: string option
      MovingStartName: string option
      MovingEndName: string option
      CreatedAt: DateTime
      UpdatedAt: DateTime }

    /// Create a new Flow (ID is auto-generated by DB)
    static member Create(flowName: string) =
        { Id = 0
          FlowName = flowName
          MT = None
          WT = None
          CT = None
          State = Some "Ready"
          MovingStartName = None
          MovingEndName = None
          CreatedAt = DateTime.UtcNow
          UpdatedAt = DateTime.UtcNow }

/// Call entity - dsp.db's dspCall table (includes statistics fields)
[<CLIMutable>]
type DspCallEntity =
    { Id: int
      CallId: Guid  // Call unique identifier (AASX Call.Id)
      CallName: string
      ApiCall: string
      WorkName: string
      FlowName: string
      Next: string option
      Prev: string option
      AutoPre: string option
      CommonPre: string option
      State: string
      ProgressRate: float
      PreviousGoingTime: int option
      AverageGoingTime: float option
      StdDevGoingTime: float option
      GoingCount: int
      Device: string option
      ErrorText: string option
      CreatedAt: DateTime
      UpdatedAt: DateTime }

    /// Create a new Call (ID is auto-generated by DB)
    static member Create(callId: Guid, callName: string, apiCall: string, workName: string, flowName: string) =
        { Id = 0
          CallId = callId
          CallName = callName
          ApiCall = apiCall
          WorkName = workName
          FlowName = flowName
          Next = None
          Prev = None
          AutoPre = None
          CommonPre = None
          State = "Ready"
          ProgressRate = 0.0
          PreviousGoingTime = None
          AverageGoingTime = None
          StdDevGoingTime = None
          GoingCount = 0
          Device = None
          ErrorText = None
          CreatedAt = DateTime.UtcNow
          UpdatedAt = DateTime.UtcNow }

/// Flow state (for UI display)
[<CLIMutable>]
type FlowState =
    { Id: int
      FlowName: string
      MT: int option
      WT: int option
      State: string
      MovingStartName: string option
      MovingEndName: string option }

/// Call state DTO (for UI display)
[<CLIMutable>]
type CallStateDto =
    { Id: int
      CallName: string
      FlowName: string
      WorkName: string
      State: string
      ProgressRate: float
      GoingCount: int
      AverageGoingTime: float option
      Device: string option
      ErrorText: string option }

/// DSP Database snapshot (used by DspDbService)
type DspDbSnapshot =
    { Flows: FlowState list
      Calls: CallStateDto list
      CallsByFlow: Map<string, CallStateDto list>
      Timestamp: DateTimeOffset }

    static member Empty =
        { Flows = []
          Calls = []
          CallsByFlow = Map.empty
          Timestamp = DateTimeOffset.UtcNow }
