namespace Ds2.LightHouse.Extractors.XlsxStrategies

open System
open Ds2.LightHouse
open Ds2.LightHouse.Diagnostics

/// **PR-I1 (todo-documents-based-gfm.md §2 + documents-based-gfm.md §8.5)** — xlsx strategy interface SSOT.
///
/// 입력 = OoxmlExtractor 가 추출한 `ExtractedDocument` (DocType=Xlsx) + source 경로 (cross-ref-hash 계산용).
/// 출력 = signature 매치 + 변환 성공 시 markdown string, 미매치 또는 변환 실패 시 RejectedEntry.
///
/// strategy 구현체는 `XlsxSignatureClassifier` 의 strategy list 에 등록. 각 strategy 는:
///   1. `Signature` — 입력의 sheet/segment 패턴 분석 후 매치 여부 + 점수 반환 (`SignatureResult`).
///   2. `Build` — 매치 시 호출, markdown 생성 (`documents-based-gfm.md` §8.5.5 머리말 5행 포맷 강제).
///
/// signature 미매치는 exception 이 아닌 정상 분기 (Result 의 Error). 변환 단계의 정상 reject 도 동일.
/// 진정한 예외 (예: 손상된 input 의 NRE) 는 reraise → fail-fast 정합 (CLAUDE.md).

/// signature 평가 결과. score = 합산 점수, threshold = 매치 최소 점수.
/// `Matched` = score >= threshold. caller 가 near-miss 판정 (score > 0 && not Matched).
type SignatureResult = {
    Matched: bool
    Score: int
    Threshold: int
    /// 점수 산출 상세 (사용자 진단용 한국어). NearMissEntry.Detail 에 박제.
    Detail: string
}

/// strategy 의 변환 결과 — 성공 시 markdown, 실패 시 RejectedEntry.
type StrategyOutcome =
    | Built of markdown: string
    | Rejected of RejectedEntry

/// xlsx strategy 의 공통 contract. `Name` / `Version` 은 머리말 `<!-- generated by <Name> v<Version> -->` 박제용.
type IXlsxStrategy =
    /// strategy 의 사람-읽는 이름 (`IoListStrategy`, `WorkOrderStrategy` 등).
    abstract member Name : string
    /// semver string (예: `"1.0.0"`). MAJOR bump 시 기존 색인 stale 처리 (M11 / §8.5.8).
    abstract member Version : string
    /// 입력 xlsx 의 signature 매치 평가. 변환 단계 진입 여부 결정.
    abstract member Signature : ExtractedDocument -> SignatureResult
    /// signature 매치 후 markdown 빌드 진입점. `sourcePath` = cross-ref-hash 계산 + diagnostic 식별용.
    /// **라운드 3 Major-4 fix**: classifier 가 평가한 `sigResult` 를 forward — strategy 가 동일
    /// `evaluateSignature` 를 다시 호출하던 중복 비용 제거. caller (classifier) 가 매치 분기 판단
    /// 후 호출하므로 Build 진입 시 `sigResult.Matched = true` 가 invariant.
    abstract member Build : sourcePath: string * extracted: ExtractedDocument * sigResult: SignatureResult -> StrategyOutcome
