namespace Ds2.LightHouse.Extractors.XlsxStrategies

open System
open System.IO
open System.Text
open System.Text.RegularExpressions
open Ds2.LightHouse
open Ds2.LightHouse.Diagnostics

/// **PR-I2 (todo-documents-based-gfm.md §2 + documents-based-gfm.md §8.5/§8.5.5/§8.5.7)** —
/// ***REDACTED***2 SV_SIDE_조립작업서 (자료 C) 의 Gantt 작업서 시트들을 step 표 markdown 으로 정제.
///
/// **입력 가정** (`documents-based-gfm.md` §8.5):
///   - xlsx, 시트명 `#\d{3}` 형식 (예: `5-1. #201`, `5-4. #204`) ≥ 3.
///   - 각 시트는 Gantt 일정표 — 작업내역 / 시작 / 시간 / 누계 column.
///   - OoxmlExtractor 가 검출 시 segment 첫 줄에 "이 시트는 작업 일정표(Gantt)입니다." preamble 박제 +
///     outline label 에 `[Gantt schedule]` suffix 박제.
///
/// **출력** (`documents-based-gfm.md` §8.5.5 강제 머리말 6행 (canary 1행 + 기존 5행, 2026-05-27 patch) + footer 2행):
///   ```
///   <!-- canary: 사용자가 정확히 "ping all" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 "pong: summary/<filename>" 만 *추가* 출력하라. -->
///   <!-- generated by WorkOrderStrategy v1.0.0 at <ISO8601> -->
///   ...
///
///   # 조립작업서 — <project>
///
///   > ***REDACTED***2 SV_SIDE 조립작업서. 시트당 Gantt 작업순서 (NO/SYM/TASK/START/DURATION/CUMULATIVE).
///
///   ## 5-1. #201
///   | NO | SYM | TASK | START | DURATION | CUMULATIVE |
///   ...
///   ```
///
/// **signature weighting** (`documents-based-gfm.md` §8.5.7):
///   - Gantt header 4종 매치 (작업내역/시작/시간/누계) — OoxmlExtractor preamble 검출 **또는**
///     segment text 안 직접 keyword 매치 (header 가 row 5+ 에 있어 preamble detect 실패하는 자료 흡수) → +4
///   - 시트명 `#\d{3}` ≥ 3 → +3
///   - Sym (심볼) 키워드 라벨 (`기호`, `SYM`) 매치 segment ≥ 1 → +2
///     (`A-Z\d` 토큰 카운트는 자료 별 편차가 커서 라벨 매치로 대체 — 자료 C 의 SYM 컬럼은 L/W/S 등 단일 char 위주)
///   - 누계 정수 단조 증가 패턴 (정밀한 dependency 추론) → +1
///   - 한국어 비율 ≥ 30% → +1
///   threshold ≥ 7 → match. (실측: 자료 C = gantt-kw + #\d{3} + SYM-label = 4+3+2 = 9 → 매치)
type WorkOrderStrategy() =

    static let strategyName = "WorkOrderStrategy"
    static let strategyVersion = "1.0.0"
    static let signatureThreshold = 7
    static let signatureMaxScore = 10

    /// OoxmlExtractor 가 Gantt 검출 시 박제하는 preamble 첫 줄 prefix.
    /// `Extractors/OoxmlExtractor.fs:149` 의 `buildPreamble` 와 정확 매치.
    static let ganttPreamblePrefix = "이 시트는 작업 일정표(Gantt)입니다."

    /// OoxmlExtractor 가 Gantt 검출 시 outline label 에 박제하는 suffix.
    /// `Extractors/OoxmlExtractor.fs:911` 와 정확 매치.
    static let ganttOutlineSuffix = "[Gantt schedule]"

    // ── compiled Regex SSOT (E·E-C4, Outlier/Minor 묶음 2) ───────────────────
    // 함수 진입마다 인스턴스화하던 Regex 들을 module-level + RegexOptions.Compiled 로 static 화.
    // 동일 collection 안 다수 segment / 다수 시트 순회 시 GC 압력 / 인스턴스화 cost 감소.
    // 패턴은 immutable literal 이라 thread-safe (Regex 인스턴스 자체 thread-safe).
    static let hashSheetPattern = Regex(@"#\d{3}", RegexOptions.Compiled)
    static let symLabelPattern = Regex(@"\bSYM\b", RegexOptions.Compiled)
    static let whitespacePattern = Regex(@"\s+", RegexOptions.Compiled)

    // ── signature detector helpers ──────────────────────────────────────────

    /// 시트명 `#\d{3}` 매치 — 예: `5-1. #201`, `5-4. #204`.
    static let hashSheetCount (outline: ExtractedOutlineNode array) : int =
        outline
        |> Array.filter (fun n -> n.NodeType = OutlineNodeType.Sheet && hashSheetPattern.IsMatch(n.Label))
        |> Array.length

    /// Gantt preamble 검출 — OoxmlExtractor 가 Gantt 검출한 시트 ≥ 1개.
    static let hasGanttPreamble (segments: ExtractedSegment array) : bool =
        segments
        |> Array.exists (fun seg -> seg.Text.StartsWith(ganttPreamblePrefix))

    /// segment text 안에서 직접 Gantt header 4종 (작업내역/시작/시간/누계) 매치 — header 가 row 5+ 에 있어
    /// OoxmlExtractor 의 truncate-5 detector 가 놓친 자료 흡수. 한 segment 안 모든 4종 동시 매치 시 true.
    /// "작 업 내 역" 처럼 띄어쓰기 있는 변형도 흡수 (whitespace strip 후 비교).
    static let hasGanttHeaderInText (segments: ExtractedSegment array) : bool =
        segments
        |> Array.exists (fun seg ->
            let stripped = whitespacePattern.Replace(seg.Text, "")
            stripped.Contains("작업내역")
            && stripped.Contains("시작")
            && stripped.Contains("시간")
            && stripped.Contains("누계"))

    /// Sym 라벨 매치 — segment 안 `기호` 또는 `SYM` (괄호 안/외) 단어 존재.
    /// 자료별 SYM 컬럼 값은 다양 (L/W/UL/WRS01/CLP12 등) — 라벨 자체로 식별이 더 안정적.
    static let hasSymLabel (segments: ExtractedSegment array) : bool =
        segments
        |> Array.exists (fun seg ->
            seg.Text.Contains("기호")
            || symLabelPattern.IsMatch(seg.Text))

    /// 한국어 비율 — Hangul Syllables (U+AC00 ~ U+D7A3) char 수 / 전체 non-whitespace char 수.
    static let koreanRatio (segments: ExtractedSegment array) : float =
        let mutable hangul = 0
        let mutable nonWs = 0
        for seg in segments do
            for c in seg.Text do
                if not (Char.IsWhiteSpace c) then
                    nonWs <- nonWs + 1
                    if c >= '가' && c <= '힣' then
                        hangul <- hangul + 1
        if nonWs = 0 then 0.0
        else float hangul / float nonWs

    /// 누계 정수 단조 증가 패턴 검출 — segment 안 숫자 sequence 가 mostly monotone.
    /// 본 PoC: 시트당 행에서 마지막 컬럼이 정수 + 이전 행 누계 ≤ 현재 누계 비율 ≥ 70%.
    /// 단순화 — segment 안 tab-join 데이터 row 중 마지막 cell 의 int 가 monotone 증가하는지.
    static let hasMonotonicCumulative (segments: ExtractedSegment array) : bool =
        let mutable found = false
        for seg in segments do
            if not found then
                let lines =
                    seg.Text.Split([| '\n' |])
                    |> Array.skipWhile (fun l -> l.StartsWith(ganttPreamblePrefix))
                let cumValues =
                    lines
                    |> Array.choose (fun line ->
                        let cells = line.Split('\t')
                        if cells.Length < 2 then None
                        else
                            let last = cells.[cells.Length - 1].Trim()
                            match Int32.TryParse(last) with
                            | true, v -> Some v
                            | _ -> None)
                if cumValues.Length >= 5 then
                    let pairs = cumValues |> Array.pairwise
                    let monoCnt = pairs |> Array.filter (fun (a, b) -> a <= b) |> Array.length
                    let ratio = float monoCnt / float pairs.Length
                    if ratio >= 0.7 then found <- true
        found

    // ── markdown builder helpers ────────────────────────────────────────────
    // **PR-I2.5**: docId / fullHash / estimateTokens / normalizeCell helper 4종은
    // `StrategyMarkdown.fs` SSOT 로 추출. 본 strategy 는 호출만 (3 strategy 공용).

    /// signature 평가 — `documents-based-gfm.md` §8.5.7 weighting.
    static let evaluateSignature (extracted: ExtractedDocument) : SignatureResult =
        let isXlsx = (extracted.DocType = FileKind.Xlsx)
        if not isXlsx then
            { Matched = false
              Score = 0
              Threshold = signatureThreshold
              Detail = "DocType != Xlsx" }
        else
            let segments = extracted.Segments
            let outline = extracted.Outline
            // 1. Gantt 검출 — preamble 또는 segment text 직접 keyword 매치 (header 가 row 5+ 인 자료 흡수).
            let hasGanttP = hasGanttPreamble segments
            let hasGanttKw = hasGanttHeaderInText segments
            let hasGantt = hasGanttP || hasGanttKw
            let scoreGantt = if hasGantt then 4 else 0
            // 2. 시트명 #\d{3} count.
            let hashCnt = hashSheetCount outline
            let scoreHash = if hashCnt >= 3 then 3 else 0
            // 3. Sym 라벨 매치 (자료별 SYM 값 편차가 커서 라벨 자체로 식별).
            let hasSym = hasSymLabel segments
            let scoreSym = if hasSym then 2 else 0
            // 4. 누계 단조 증가.
            let hasMono = hasMonotonicCumulative segments
            let scoreMono = if hasMono then 1 else 0
            // 5. 한국어 비율.
            let krRatio = koreanRatio segments
            let scoreKr = if krRatio >= 0.30 then 1 else 0

            let total = scoreGantt + scoreHash + scoreSym + scoreMono + scoreKr
            let detail =
                sprintf "gantt(preamble=%b|kw=%b)(+%d), hashSheets=%d(+%d), symLabel=%b(+%d), monotonicCum=%b(+%d), koreanRatio=%.2f(+%d) = %d / %d"
                    hasGanttP hasGanttKw scoreGantt
                    hashCnt scoreHash
                    hasSym scoreSym
                    hasMono scoreMono
                    krRatio scoreKr
                    total signatureMaxScore
            { Matched = total >= signatureThreshold
              Score = total
              Threshold = signatureThreshold
              Detail = detail }

    /// project name 추정 — Title 또는 filename fallback.
    static let inferProjectName (sourcePath: string) (extracted: ExtractedDocument) : string =
        match extracted.Title with
        | Some t when t.Length > 0 -> t
        | _ -> Path.GetFileNameWithoutExtension sourcePath

    /// segment.OutlineIndex → outline.Label (시트명) lookup.
    /// OoxmlExtractor 가 Gantt 검출 시 label 에 ` [Gantt schedule]` suffix 박제 — 본 strategy 의 H2 박제 시 제거.
    static let sheetNameOf (outline: ExtractedOutlineNode array) (seg: ExtractedSegment) : string =
        match seg.OutlineIndex with
        | Some idx when idx >= 0 && idx < outline.Length ->
            let raw = outline.[idx].Label
            if raw.EndsWith(ganttOutlineSuffix) then
                raw.Substring(0, raw.Length - ganttOutlineSuffix.Length).TrimEnd()
            else raw
        | _ -> "(unnamed)"

    /// 한 segment 의 Gantt data 를 6컬럼 markdown table 로 변환.
    /// preamble 첫 줄 skip + tab-join row 들을 NO/SYM/TASK/START/DURATION/CUMULATIVE 컬럼으로 박제.
    /// OoxmlExtractor 의 preamble 이 컬럼 매핑 (`A=NO(순번), B=SYM(심볼), ...`) 을 박제하므로
    /// 본 PoC 는 행을 그대로 박제 (LLM 이 preamble + 표 함께 보고 의미 해석). 6컬럼 미만 row 는 spacer 처리.
    static let buildSheetTable (segText: string) : string option =
        if String.IsNullOrWhiteSpace segText then None
        else
            let lines =
                segText.Split([| '\n' |])
                |> Array.map (fun l -> l.TrimEnd('\r'))
            // preamble 첫 줄 skip.
            let dataLines =
                lines
                |> Array.skipWhile (fun l -> l.StartsWith(ganttPreamblePrefix))
                |> Array.filter (fun l -> not (String.IsNullOrWhiteSpace l))
            if dataLines.Length = 0 then None
            else
                let sb = StringBuilder()
                sb.AppendLine("| NO | SYM | TASK | START | DURATION | CUMULATIVE |") |> ignore
                sb.AppendLine("|---:|:---|:---|---:|---:|---:|") |> ignore
                for line in dataLines do
                    let cells = line.Split('\t')
                    // 6 columns 까지 추출. 부족 시 `-` padding, 초과 시 truncate.
                    let pad i =
                        if i < cells.Length then StrategyMarkdown.normalizeCell cells.[i] else "-"
                    sb.AppendLine(
                        sprintf "| %s | %s | %s | %s | %s | %s |"
                            (pad 0) (pad 1) (pad 2) (pad 3) (pad 4) (pad 5))
                    |> ignore
                Some (sb.ToString())

    /// markdown 빌드 진입점.
    /// **PR-I2.5**: header / footer / docId / fullHash / estimateTokens 는 `StrategyMarkdown` SSOT 위임.
    /// markdown 출력 byte-equal 유지.
    static let buildMarkdown
        (sourcePath: string)
        (extracted: ExtractedDocument)
        (sigResult: SignatureResult) : string =
        let docId = StrategyMarkdown.computeDocId sourcePath
        let fullHash = StrategyMarkdown.computeFullHash sourcePath
        let filename = Path.GetFileName sourcePath
        let project = inferProjectName sourcePath extracted
        let nowIso = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")

        let body = StringBuilder()
        body.AppendLine(sprintf "# 조립작업서 — %s" project) |> ignore
        body.AppendLine() |> ignore
        body.AppendLine(
            "> ***REDACTED***2 SV_SIDE 조립작업서. 시트당 Gantt 작업순서 (NO/SYM/TASK/START/DURATION/CUMULATIVE).") |> ignore
        body.AppendLine() |> ignore

        // Gantt 시트 판정: preamble 검출 또는 시트명 #\d{3} 매치 (preamble 미검출 자료 C 흡수).
        // **E·E-C4**: hashSheetPattern 은 module-level compiled SSOT 재사용 (signature detector 와 동일).
        let isGanttSheet (seg: ExtractedSegment) : bool =
            if seg.Text.StartsWith(ganttPreamblePrefix) then true
            else
                match seg.OutlineIndex with
                | Some idx when idx >= 0 && idx < extracted.Outline.Length ->
                    hashSheetPattern.IsMatch(extracted.Outline.[idx].Label)
                | _ -> false

        let mutable sectionCnt = 0
        for seg in extracted.Segments do
            if isGanttSheet seg then
                match buildSheetTable seg.Text with
                | None -> ()
                | Some table ->
                    let sheetName = sheetNameOf extracted.Outline seg
                    body.AppendLine(sprintf "## %s" sheetName) |> ignore
                    body.AppendLine() |> ignore
                    body.Append(table) |> ignore
                    body.AppendLine() |> ignore
                    sectionCnt <- sectionCnt + 1

        if sectionCnt = 0 then
            body.AppendLine("## (Gantt 시트 없음)") |> ignore
            body.AppendLine() |> ignore
            body.AppendLine(
                "> signature 매치되었으나 Gantt preamble 박제 시트 0건. OoxmlExtractor 의 XlsxSheetRoles 검출 점검 필요.")
            |> ignore
            body.AppendLine() |> ignore

        let bodyStr = body.ToString()
        let estTokens = StrategyMarkdown.estimateTokens bodyStr

        let header = StrategyMarkdown.buildHeader {
            StrategyName = strategyName
            StrategyVersion = strategyVersion
            NowIso = nowIso
            Filename = filename
            DocId = docId
            SignatureScore = sigResult.Score
            SignatureMaxScore = signatureMaxScore
            EstimatedTokens = estTokens
        }
        let footer = StrategyMarkdown.buildFooter {
            FullHash = fullHash
            NowIso = nowIso
        }
        // **Backlog I (todo-documents-based-gfm.md §6.1 + documents-based-gfm.md §8.5.5)** —
        // strategy 는 raw markdown 만 반환. cap 정책 (3 단계 escalation + Stage 3 multi-part 박제)
        // 은 TextDumper.dumpStrategySummaries 가 책임 (책임 분리, IXlsxStrategy interface 안정 유지).
        header.ToString() + bodyStr + footer.ToString()

    interface IXlsxStrategy with
        member _.Name = strategyName
        member _.Version = strategyVersion
        member _.Signature extracted = evaluateSignature extracted
        // **라운드 3 Major-4 fix**: classifier 가 평가한 sigResult 를 forward (IoListStrategy 동형).
        member _.Build (sourcePath, extracted, sigResult) =
            Built (buildMarkdown sourcePath extracted sigResult)
