module Ds2.Aasx.AasxSemantics

let [<Literal>] SubmodelIdShort  = "Ds2SequenceControlSubmodel"
let [<Literal>] Name_            = "Name"
let [<Literal>] Guid_            = "Guid"
let [<Literal>] Properties_      = "Properties"
let [<Literal>] IsActive_        = "IsActiveSystem"
let [<Literal>] ActiveSystems_   = "ActiveSystems"
let [<Literal>] PassiveSystems_  = "PassiveSystems"
let [<Literal>] Flows_           = "Flows"
let [<Literal>] Works_           = "Works"
let [<Literal>] Calls_           = "Calls"
let [<Literal>] ApiDefs_         = "ApiDefs"
let [<Literal>] ApiCalls_        = "ApiCalls"
let [<Literal>] CallConditions_  = "CallConditions"
let [<Literal>] ArrowsBtWorks_   = "ArrowsBetweenWorks"
let [<Literal>] ArrowsBtCalls_   = "ArrowsBetweenCalls"
let [<Literal>] DevicesAlias_    = "DevicesAlias"
let [<Literal>] ApiName_         = "ApiName"
let [<Literal>] Position_        = "Position"
let [<Literal>] Status_          = "Status"
let [<Literal>] ArrowType_       = "ArrowType"
let [<Literal>] SourceId_        = "SourceId"
let [<Literal>] TargetId_        = "TargetId"
