module Ds2.Aasx.AasxSemantics

let [<Literal>] SubmodelIdShort      = "SequenceControlSubmodel"
let [<Literal>] SubmodelSemanticId   = "https://dualsoft.com/aas/submodel"
let [<Literal>] Name_                = "Name"
let [<Literal>] Guid_                = "Guid"
let [<Literal>] Properties_          = "Properties"
let [<Literal>] ActiveSystems_       = "ActiveSystems"
let [<Literal>] IRI_                 = "IRI"
let [<Literal>] Flows_               = "Flows"
let [<Literal>] Works_               = "Works"
let [<Literal>] Arrows_              = "Arrows"
let [<Literal>] Calls_               = "Calls"
let [<Literal>] ApiDefs_             = "ApiDefs"
let [<Literal>] ApiCalls_            = "ApiCalls"
let [<Literal>] ReferencedApiDefs_   = "ReferencedApiDefs"
let [<Literal>] DeviceReferences_    = "DeviceReferences"
let [<Literal>] PassiveSystems_      = "PassiveSystems"    // 구버전 호환 폴백용
let [<Literal>] CallConditions_      = "CallConditions"
let [<Literal>] DevicesAlias_        = "DevicesAlias"
let [<Literal>] ApiName_             = "ApiName"
let [<Literal>] Position_            = "Position"
let [<Literal>] Status_              = "Status"
let [<Literal>] FlowGuid_            = "FlowGuid"
let [<Literal>] Source_              = "Source"
let [<Literal>] Target_              = "Target"
let [<Literal>] Type_                = "Type"
