<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Ds2TextLexeme.fs" />
    <Compile Include="Ds2TextSpec.fs" />
    <Compile Include="Ds2TextWriter.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Ds2.Core\Ds2.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

</Project>
