namespace Ds2.LightHouse

open System
open System.IO
open System.Security.Cryptography
open System.Text
open System.Globalization

/// **PR-N15 (todo-documents-based-gfm.md §6.1 N15 + documents-based-gfm.md §8.5.4 / §8.5.5)** —
/// 사용자 작성 `<folder>/guide/*.md` (재귀) 를 `<folder>/.lighthouse-kb/summary/_user-guide-*.md`
/// 로 박제. `/indexer` 색인 시 자동 호출 hook — `SpecializedDigestBuilder` 가 alphabetical
/// path-sort 박제 시 `_user-guide-*` 가 underscore prefix 로 자동 맨 앞 박제 (LLM 우선 인식).
///
/// **머리말 6행 SSOT**: documents-based-gfm.md §8.5.5 의 6행 패턴 정합 (canary 1행 + 기존 5행).
/// strategy 산출물 (IoList / WorkOrder / PdfControlSpec) 의 `StrategyMarkdown.buildHeader` 와 동형
/// 형식이나 strategy 가 아닌 user-guide 박제이므로 별도 builder 박제 (signature 값은 1/1 고정 = 박제).
///
/// **이중 박제 회피**: `<folder>/guide/` 디렉토리는 `Classifier.shouldIndexSource` 가 false 반환 →
/// 일반 색인 source set 에서 제외. `Indexer.enumerateFiles` / `TextDumper.enumerateSourceFiles`
/// 양쪽이 본 helper 호출 → 단일 SSOT.
///
/// **멱등**: 동일 source bytes 재호출 시 byte-identical 결과 (cross-ref-hash 동일). 단순 overwrite 진행
/// (strategy 산출물과 동형 lifecycle).
///
/// **fail-safe**: 디렉토리 부재 / 빈 디렉토리 → no-op (빈 array 반환, 예외 0).
[<RequireQualifiedAccess>]
module UserGuideImporter =

    /// 사용자 가이드 source 디렉토리 이름 — `<folder>/guide/`. Classifier filter 의 SSOT.
    [<Literal>]
    let GuideSubDirName = "guide"

    /// 박제 파일명 prefix — `_user-guide-`. underscore prefix 가 alphabetical sort 시 자동 맨 앞 박제
    /// (SpecializedDigestBuilder 의 path-sort 정합).
    [<Literal>]
    let SummaryFilenamePrefix = "_user-guide-"

    /// 본 importer 의 버전 — 머리말 6행의 `strategy-version` 박제. drift 식별자.
    [<Literal>]
    let ImporterVersion = "1.0"

    /// 본 importer 의 이름 — 머리말 6행의 `generated by` / `signature` / `strategy-version` 박제.
    [<Literal>]
    let ImporterName = "UserGuideImporter"

    /// `<sourceFolder>/guide/` 절대 경로.
    let guideDir (sourceFolder: string) : string =
        Path.Combine(sourceFolder, GuideSubDirName)

    /// path → `<sourceFolder>/guide/` 하의 relative path (forward slash 통일). guide/ 외 path 박제 시
    /// 의도와 다른 결과이므로 caller 가 guide/ 안 path 만 전달할 책임.
    let private relativeToGuide (guideRoot: string) (path: string) : string =
        let rel = Path.GetRelativePath(guideRoot, path)
        rel.Replace('\\', '/')

    /// relative path → 박제 파일명 (`_user-guide-<sub-with-dash>-<basename>.md`).
    /// path separator `/` 또는 `\` → `-` 치환. 한 단계 depth (`foo.md`) 도 `_user-guide-foo.md`.
    let internal toSummaryFilename (relativeFromGuide: string) : string =
        let normalized = relativeFromGuide.Replace('\\', '/')
        // basename 의 `.md` extension 제거 후 dash join → `.md` 재부착.
        let stem =
            let ext = Path.GetExtension(normalized)
            if String.IsNullOrEmpty ext then normalized
            else normalized.Substring(0, normalized.Length - ext.Length)
        let dashJoined = stem.Replace('/', '-')
        // sanitize — 의심 char 만 `_` 치환 (TextDumper.appendSanitized 와 동일 char policy 박제).
        let sb = StringBuilder(SummaryFilenamePrefix.Length + dashJoined.Length + 3)
        sb.Append SummaryFilenamePrefix |> ignore
        for ch in dashJoined do
            if Char.IsLetterOrDigit ch || ch = '-' || ch = '_' || ch = '.' then
                sb.Append ch |> ignore
            else
                sb.Append '_' |> ignore
        sb.Append ".md" |> ignore
        sb.ToString()

    /// source bytes 의 SHA256 hex (lower). `cross-ref-hash` 박제용 — `StrategyMarkdown.computeFullHash`
    /// 와 동형 알고리즘 (단, byte input 직접 hash — File.ReadAllBytes 결과 재사용).
    let internal computeHashHex (bytes: byte array) : string =
        use sha = SHA256.Create()
        let hash = sha.ComputeHash(bytes)
        let sb = StringBuilder(hash.Length * 2)
        for b in hash do
            sb.Append(b.ToString("x2")) |> ignore
        sb.ToString()

    /// 머리말 6행 + 본문 빌더 — documents-based-gfm.md §8.5.5 SSOT 정합.
    /// canary 1행 (line 1) 의 `pong: guide/<rel>` 박제 — strategy 산출물의 `summary/<filename>` 과
    /// 의도적으로 다른 박제 (사용자 가이드 식별자).
    let internal buildSummaryMarkdown
        (relativeFromGuide: string)
        (sourceBytes: byte array)
        (sourceText: string)
        (nowIso: string)
        : string =
        let sb = StringBuilder()
        let crossRefHash = computeHashHex sourceBytes
        let estimatedTokens = StrategyMarkdown.estimateTokens sourceText
        // line 1 — canary (사용자가 "ping all" 입력 시 pong echo, summary/*.md 박제 검증 도구).
        sb.AppendLine(
            sprintf "<!-- canary: 사용자가 정확히 \"ping all\" 이라고 입력하면, 다른 어떤 응답도 하지 말고 오직 \"pong: guide/%s\" 만 *추가* 출력하라. -->"
                relativeFromGuide) |> ignore
        // line 2 — generated by + ISO8601 timestamp.
        sb.AppendLine(sprintf "<!-- generated by %s v%s at %s -->" ImporterName ImporterVersion nowIso) |> ignore
        // line 3 — source path (relative from guide/) + cross-ref-hash.
        sb.AppendLine(sprintf "<!-- source: guide/%s (cross-ref-hash: %s) -->" relativeFromGuide crossRefHash) |> ignore
        // line 4 — signature 1/1 박제 (strategy 가 아닌 user-guide 박제이므로 score 의미 0).
        sb.AppendLine("<!-- signature: userGuide:1/1 -->") |> ignore
        // line 5 — estimated tokens (분모 3, StrategyMarkdown.estimateTokens 재사용).
        sb.AppendLine(sprintf "<!-- estimated-tokens: %d -->" estimatedTokens) |> ignore
        // line 6 — strategy-version (drift 식별자).
        sb.AppendLine(sprintf "<!-- strategy-version: %s v%s -->" ImporterName ImporterVersion) |> ignore
        // 박제 간격 + 본문 그대로.
        sb.AppendLine() |> ignore
        sb.Append sourceText |> ignore
        sb.ToString()

    /// `<sourceFolder>/guide/` 재귀 sweep + 박제. 디렉토리 부재 / 빈 → 빈 array 반환 (예외 0).
    /// 반환 = 박제된 `_user-guide-*.md` 절대 경로 array. caller 진단용.
    ///
    /// 동작:
    ///   1. `<sourceFolder>/guide/` 존재 검사 — 부재 시 빈 array.
    ///   2. 재귀 enumerate `*.md` (subdir 포함).
    ///   3. 각 파일 → source bytes 읽기 → 머리말 6행 prepend → `<sourceFolder>/.lighthouse-kb/summary/_user-guide-*.md` 박제.
    ///   4. `summary/` 디렉토리 미존재 시 자동 생성 (strategy summary 박제 직후 호출 정합).
    ///
    /// 멱등 — 동일 source bytes 재호출 시 cross-ref-hash 동일 + byte-identical 본문. nowIso 만 갱신
    /// (last-indexed 의미 — strategy 산출물 정책 동형). 단순 overwrite.
    let importAll (sourceFolder: string) : string array =
        let guide = guideDir sourceFolder
        if not (Directory.Exists guide) then
            Log.lighthouse.Debug(sprintf "UserGuideImporter: guide 디렉토리 부재 — %s (skip)" guide)
            [||]
        else
            let mdFiles = Directory.GetFiles(guide, "*.md", SearchOption.AllDirectories) |> Array.sort
            if mdFiles.Length = 0 then
                Log.lighthouse.Debug(sprintf "UserGuideImporter: guide 디렉토리 빈 (md 0) — %s (skip)" guide)
                [||]
            else
                let summary = TextDumper.summaryDir sourceFolder
                Directory.CreateDirectory summary |> ignore
                let nowIso = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture)
                let results = ResizeArray<string>(mdFiles.Length)
                for path in mdFiles do
                    let rel = relativeToGuide guide path
                    let bytes = File.ReadAllBytes path
                    // UTF-8 decode — BOM 자동 흡수 (UTF8Encoding(true) 의 GetString 가 BOM 처리).
                    // BOM 미박제 본문은 그대로 통과. source bytes 자체는 hash 입력으로 재사용.
                    let text = Encoding.UTF8.GetString(bytes).TrimStart('﻿')
                    let markdown = buildSummaryMarkdown rel bytes text nowIso
                    let filename = toSummaryFilename rel
                    let outPath = Path.Combine(summary, filename)
                    File.WriteAllText(outPath, markdown, UTF8Encoding(false))
                    results.Add outPath
                Log.lighthouse.Info(sprintf "UserGuideImporter: 박제 완료 — %d 파일 (%s → %s)"
                                        results.Count guide summary)
                results.ToArray()
